/* ============================================================
   NWC Artifacts Page
   ============================================================ */
(function () {
  renderNav("Artifacts");

  // ============================================================
  // ALL ARTIFACTS DATA
  // ============================================================
  var artifacts = [
    // -- Group Debuff --
    { name: "Halaster's Blast Scepter", type: "debuff", power: "Single-target stun. Reduces target's damage resistance by 15% for 10s.", debuff: "15% damage resistance reduction", cooldown: 60, set: "Mad Dash", source: "Tower of the Mad Mage", image: "images/artifacts/Icon_Inventory_Artifact_Halaster.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":900},{"stat":"Critical Strike","value":450}] },
    { name: "Wyvern-Venom Coated Knives", type: "debuff", power: "AoE knives + poison DoT. Envenomated enemies take 12% more damage and deal 12% less damage for 10s.", debuff: "12% more damage taken + 12% less damage dealt", cooldown: 60, set: "Armaments of the Wyvern", source: "Undermountain Campaign", image: "images/artifacts/Icon_Inventory_Artifact_Wyvernknives.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Critical Severity","value":450},{"stat":"Critical Strike","value":450},{"stat":"Accuracy","value":900}] },
    { name: "Frozen Storyteller's Journal", type: "debuff", power: "25' AoE damage. Stuns 3s. Summons 3 ice dwarves (20s). Allies deal 10% more damage. Incoming damage reduced 10% for 15s.", debuff: "10% party damage buff + 10% damage reduction", cooldown: 60, set: "Storyteller's Journals", source: "Zen Market / Tales of Old", image: "images/artifacts/Icon_Inventory_Artifacts_Storytellers_Journal_Frozen.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":450},{"stat":"Critical Severity","value":450},{"stat":"Critical Avoidance","value":450}] },
    { name: "Charm of the Serpent", type: "debuff", power: "Cone attack. Targets take 16% more damage for 10s.", debuff: "16% more damage taken (cone)", cooldown: 60, set: "Set of the Serpent", source: "Tomb of the Nine Gods", image: "images/artifacts/Icon_Inventory_Artifacts_Crownoftheserpent.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Severity","value":450},{"stat":"Critical Avoidance","value":450}] },
    { name: "Lantern of Revelation", type: "debuff", power: "AoE damage. Targets take 10% more damage for 10s. Reveals hidden enemies.", debuff: "10% more damage taken", cooldown: 60, set: "None", source: "Quest reward", image: "images/artifacts/Icon_Inventory_Artifacts_LanternOfRevelation.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Severity","value":450},{"stat":"Critical Strike","value":450},{"stat":"Combat Advantage","value":450}] },
    { name: "Thirst", type: "debuff", power: "Lunge forward dealing line damage. Enemies take 10% more damage for 10s.", debuff: "10% more damage taken (lunge)", cooldown: 60, set: "None", source: "Castle Ravenloft", image: "images/artifacts/Inventory_Primary_Cormyrean_Longsword.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":450},{"stat":"Defense","value":450}] },
    { name: "Heart of the Black Dragon", type: "debuff", power: "Line AoE acid damage to 7 enemies + DoT. Enemies take 10% more damage for 6s.", debuff: "10% more damage taken (6s)", cooldown: 60, set: "Hearts of the Dragons", source: "Dungeon drop", image: "images/artifacts/Icon_Inventory_Artifacts_Black_Dragon_Heart.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Severity","value":450},{"stat":"Accuracy","value":450},{"stat":"Awareness","value":450}] },
    { name: "Token of Chromatic Storm", type: "debuff", power: "9 chromatic meteors near target. Acid meteors cause 10% more damage taken for 10s. Fire = DoT, Ice = freeze.", debuff: "10% more damage taken (RNG acid)", cooldown: 60, set: "None", source: "Lockbox", image: "images/artifacts/Icon_Inventory_Artifacts_Chromatic_Storm.webp", itemLevel: 600, combinedRating: 450, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":450},{"stat":"Accuracy","value":450},{"stat":"Defense","value":450},{"stat":"Awareness","value":450}] },
    { name: "Sparkling Fey Emblem", type: "debuff", power: "Field for 15s. Enemies take 5% more damage. Allies gain 5% Defense and 5% Critical Avoidance.", debuff: "5% more damage + ally defense buffs", cooldown: 60, set: "Star Set", source: "Vault of Stars", image: "images/artifacts/Icon_Inventory_Artifact_Stars.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Max HP","value":3600},{"stat":"Critical Avoidance","value":450},{"stat":"Forte","value":450}] },
    { name: "Vanguard's Banner", type: "debuff", power: "Banner for 30s. Allies gain 5,000 Power and 5,000 Crit Avoidance. Foes take 5% more damage.", debuff: "5% more damage + ally Power buff (30s)", cooldown: 60, set: "None", source: "PVP (40k Glory)", image: "images/artifacts/Icon_Inventory_Artifacts_VanguardBanner.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":450},{"stat":"Critical Avoidance","value":450}] },
    { name: "Refulgent Diamond Pin", type: "debuff", power: "AoE damage. Enemies deal 5% less damage for 15s. Allies gain 7.5% Combat Advantage for 15s.", debuff: "5% less enemy damage + 7.5% ally CA", cooldown: 60, set: "Diamond Set", source: "Shattered Diamonds", image: "images/artifacts/Icon_Inventory_Artifact_Diamond.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Power","value":450},{"stat":"Combat Advantage","value":900},{"stat":"Critical Avoidance","value":450}] },
    { name: "Tiamat's Orb of Majesty", type: "tank", power: "Stuns monsters 4s (players 2s). Reduces their damage by 15% for 6s.", debuff: "15% less enemy damage (6s) + stun", cooldown: 60, set: "Tiamat Set", source: "Rise of Tiamat", image: "images/artifacts/Icon_Inventory_Artifacts_Tiamat_Voice.webp", itemLevel: 600, combinedRating: 450, stats: [{"stat":"Power","value":450},{"stat":"Critical Severity","value":450},{"stat":"Critical Strike","value":450},{"stat":"Accuracy","value":450},{"stat":"Awareness","value":450}] },
    { name: "Defender's Banner", type: "tank", power: "Banner for 30s. Allies gain 5,000 Power and 5,000 Awareness. Foes deal 5% less damage.", debuff: "5% less enemy damage + ally buffs (30s)", cooldown: 60, set: "None", source: "PVP (40k Glory)", image: "images/artifacts/Icon_Inventory_Artifacts_DefenderBanner.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Defense","value":450},{"stat":"Awareness","value":450},{"stat":"Incoming Healing","value":450}] },
    { name: "Erratic Drift Globe", type: "tank", power: "Orbit for 15s. Allies gain 15,000 Deflection. Foes lose 15,000 Crit Strike and 15,000 Deflection.", debuff: "Stat shred on enemies", cooldown: 60, set: "Reflective Armaments", source: "Undermountain Campaign", image: "images/artifacts/Icon_Inventory_Artifact_Driftglobe.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Max HP","value":1800},{"stat":"Defense","value":900},{"stat":"Deflect","value":450}] },
    // -- Personal DPS --
    { name: "Soul Sight Crystal", type: "personal", power: "Target takes 25% more damage from YOUR attacks only for 10s.", debuff: "25% personal damage buff (solo only)", cooldown: 60, set: "None", source: "Quest reward", image: "images/artifacts/Icon_Inventory_Artifacts_Soulsight.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Control Bonus","value":450}] },
    { name: "Arcturia's Music Box", type: "personal", power: "Summons 2 mimics dealing AoE damage. Consumes minions on hit.", debuff: "None (set bonus is the value)", cooldown: 60, set: "Apprentices' Spoils", source: "Zok boxes (Undermountain)", image: "images/artifacts/Icon_Inventory_Artifact_Musicbox.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Power","value":450},{"stat":"Critical Severity","value":450},{"stat":"Combat Advantage","value":900}] },
    { name: "Decanter of Atropal Essence", type: "personal", power: "Boon of Atropal for 20s. Powers deal extra damage per hit. Each proc: +1s duration, +1% damage, up to 10 stacks (10%).", debuff: "10% personal damage ramp", cooldown: 60, set: "Soulmonger Set", source: "Tomb of Annihilation", image: "images/artifacts/Icon_Inventory_Artifacts_Soulmonger.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Severity","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Deflect Severity","value":450}] },
    { name: "Sigil of the Barbarian", type: "personal", power: "AoE damage. YOUR damage and mitigation +14% for up to 16s (scales with targets hit).", debuff: "14% personal damage + mitigation", cooldown: 60, set: "None", source: "Vault of the Nine (Barbarian)", image: "images/artifacts/Icon_Inventory_Artifacts_Class_GreatWeapon.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":450},{"stat":"Critical Severity","value":450}] },
    { name: "Wheel of Elements", type: "personal", power: "4 elemental symbols. Fire: +5% bonus fire damage for 30s. Earth: 100% HP shield 5s. Water: heal 50% HP over 30s. Wind: CC immunity.", debuff: "5% fire damage (if correct symbol)", cooldown: 60, set: "None", source: "Elemental Evil", image: "images/artifacts/Icon_Inventory_Artifacts_Wheelofelements.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":450}] },
    { name: "Eye of the Giant", type: "personal", power: "+5,000 Power and Defense for 12s. +1,000 per enemy (up to 5). At 5+ enemies: icy blast.", debuff: "Scaling self-buff", cooldown: 60, set: "None", source: "Storm King's Thunder", image: "images/artifacts/Icon_Inventory_Artifacts_Eyeofthegiant.webp", itemLevel: 600, combinedRating: 450, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":450},{"stat":"Critical Severity","value":450},{"stat":"Critical Strike","value":450},{"stat":"Defense","value":450}] },
    // -- Tank / Mitigation --
    { name: "Horn of Valhalla", type: "tank", power: "Summons Barbarian for 30s. When enemies attack you, their damage -3% for 6s, stacks 5x (15% max).", debuff: "15% stacking enemy damage reduction", cooldown: 60, set: "Valhalla's Rebuke", source: "Assault on Svardborg", image: "images/artifacts/Icon_Inventory_Artifacts_Horn_Of_Valhalla.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Critical Strike","value":450},{"stat":"Combat Advantage","value":450}] },
    { name: "Sigil of the Paladin", type: "tank", power: "Protective field for 10s. Allies inside gain 15% damage resistance + HoT.", debuff: "15% ally damage resistance", cooldown: 60, set: "None", source: "Vault of the Nine (Paladin)", image: "images/artifacts/Icon_Inventory_Artifacts_Class_Paladin.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":450},{"stat":"Accuracy","value":450}] },
    { name: "Sigil of the Fighter", type: "tank", power: "Blocks 90% of next attack (up to 25% max HP) every second for 10s.", debuff: "90% block (self)", cooldown: 60, set: "None", source: "Vault of the Nine (Fighter)", image: "images/artifacts/Icon_Inventory_Artifacts_Class_Guardian.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Accuracy","value":450},{"stat":"Defense","value":450},{"stat":"Deflect","value":450}] },
    { name: "Forgehammer of Gond", type: "tank", power: "Damage taken halved (50% reduction) for 5s.", debuff: "50% damage reduction (5s)", cooldown: 60, set: "None", source: "Wonders of Gond", image: "images/artifacts/Icon_Inventory_Artifacts_ForgeHammerofGond.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Deflect","value":450},{"stat":"Control Resist","value":450}] },
    { name: "Gond's Anvil of Creation", type: "tank", power: "Shield for 15% of max HP. Regenerates every 3s for 15s.", debuff: "Regenerating shield", cooldown: 60, set: "None", source: "Wonders of Gond", image: "images/artifacts/Icon_Inventory_Artifacts_Anvil_Of_Creation.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Avoidance","value":450}] },
    // -- Utility / Healing --
    { name: "Sigil of the Cleric", type: "utility", power: "Fills 25% of Action Points over 15s. Heals on Encounter power use.", debuff: "AP generation + self heal", cooldown: 60, set: "None", source: "Vault of the Nine (Cleric)", image: "images/artifacts/Icon_Inventory_Artifacts_Class_Devoted.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Defense","value":450},{"stat":"Incoming Healing","value":450}] },
    { name: "Staff of Flowers", type: "utility", power: "Ring of flowers for 15s. Allies gain 15,000 Power and 15,000 Crit Strike. Foes slowed 25% + poison DoT.", debuff: "Ally Power + Crit buff zone", cooldown: 60, set: "Enchanted Thumb", source: "Zok boxes (Undermountain)", image: "images/artifacts/Icon_Inventory_Artifact_Flowerstaff.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Power","value":900},{"stat":"Critical Strike","value":450},{"stat":"Awareness","value":450}] },
    { name: "Bloodcrystal Raven Skull", type: "utility", power: "Shield = 10% max HP + 110% missing HP. Single-target heals buff target's Power and Accuracy by 5% for 5s.", debuff: "Shield + heal buff", cooldown: 60, set: "None", source: "Dungeon drop", image: "images/artifacts/Icon_Inventory_Artifacts_BloodCrystalRavenSkull.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Accuracy","value":450},{"stat":"Awareness","value":450}] },
    { name: "Eye of Lathander", type: "utility", power: "Resurrects ally or companion at 80' range. Restores 80% HP.", debuff: "Long-range resurrect", cooldown: 60, set: "Lathander Set", source: "Dread Ring / Tiamat", image: "images/artifacts/Icon_Inventory_Artifacts_EyeOfLathandar.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Defense","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Incoming Healing","value":450}] },
    { name: "Oghma's Token of Free Movement", type: "utility", power: "Removes control effects. CC immunity for 6s. Deals damage.", debuff: "CC break + immunity", cooldown: 60, set: "None", source: "Lockbox", image: "images/artifacts/Icon_Inventory_Artifacts_Oghmastrinket.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Defense","value":450},{"stat":"Deflect","value":450},{"stat":"Control Resist","value":450}] },
    { name: "Waters of Elah'zad", type: "utility", power: "Self-heal over 6s. Removes DoT effects. Not affected by PvP healing depression.", debuff: "Self-heal + DoT cleanse", cooldown: 60, set: "None", source: "Quest reward", image: "images/artifacts/Icon_Inventory_Artifacts_WatersOfElahzad.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Accuracy","value":450},{"stat":"Defense","value":450},{"stat":"Awareness","value":450}] },
    { name: "Aurora's Whole Realms Catalogue", type: "utility", power: "Out of combat: summons vendor. In combat: fire damage + stun.", debuff: "Portable vendor", cooldown: 60, set: "None", source: "Quest reward", image: "images/artifacts/Icon_Inventory_Artifacts_AurorasWholeRealmsCatalogue.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Avoidance","value":450},{"stat":"Deflect","value":450},{"stat":"Gold Bonus","value":450}] },
    // -- Damage Only --
    { name: "Lostmauth's Horn of Blasting", type: "damage", power: "Cone damage + knockback.", debuff: "None", cooldown: 60, set: "Lostmauth's Hoard", source: "Lair of Lostmauth", image: "images/artifacts/Icon_Inventory_Artifacts_Horn_Of_Blasting.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Severity","value":450},{"stat":"Control Bonus","value":450}] },
    { name: "Book of Vile Darkness", type: "damage", power: "Reduces cooldowns 1-2s. Slows nearby enemies.", debuff: "None", cooldown: 60, set: "Dark Remnant", source: "Infernal Citadel", image: "images/artifacts/Icons_Inventory_Artifacts_Bookofviledarkness.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Power","value":900},{"stat":"Critical Severity","value":450},{"stat":"Deflect","value":450}] },
    { name: "Trobriand's Ring", type: "damage", power: "Electric stun + damage. Spawns Scaladar for 15s.", debuff: "None", cooldown: 60, set: "Armaments of Construct Demise", source: "Lair of the Mad Mage", image: "images/artifacts/Icon_Inventory_Artifact_Trobriandring.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Power","value":900},{"stat":"Defense","value":450},{"stat":"Critical Avoidance","value":450}] },
    { name: "Apocalypse Dagger", type: "damage", power: "25' AoE damage.", debuff: "None (set bonus: stacking 5% group debuff on crit)", cooldown: 60, set: "Apocalypse Set", source: "Manycoins Bank Heist", image: "images/artifacts/Icon_Inventory_Artifacts_Apocalypsedagger.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Deflect","value":450},{"stat":"Forte","value":450}] },
    { name: "Shard of Orcus' Wand", type: "damage", power: "Pursuing orb deals damage. Explodes after 5 hits or 15s.", debuff: "None", cooldown: 60, set: "Demon Lords' Immortality", source: "Castle Never", image: "images/artifacts/Icon_Inventory_Artifacts_Sphereofdeath.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Accuracy","value":450},{"stat":"Critical Avoidance","value":450}] },
    { name: "Sword of Zariel", type: "damage", power: "Celestial swords rain on target. Bleed DoT 12s.", debuff: "None", cooldown: 60, set: "None", source: "Avernus content", image: "images/artifacts/Icon_Inventory_Artifact_Fallenangel.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":900},{"stat":"Critical Strike","value":450}] },
    { name: "Tarokka Deck", type: "damage", power: "Draw 3 random cards with different effects (damage, heal, buff).", debuff: "None", cooldown: 60, set: "Vistani Set", source: "Barovia / Ravenloft", image: "images/artifacts/Kits_Tarokkadeck_Box.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Severity","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Deflect Severity","value":450}] },
    // -- Sigils --
    { name: "Sigil of the Warlock", type: "utility", power: "Damages up to 5 targets. Heals you per target hit.", debuff: "Self-heal on hit", cooldown: 60, set: "None", source: "Vault of the Nine (Warlock)", image: "images/artifacts/Icon_Inventory_Artifacts_Class_Warlock.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Deflect","value":450}] },
    { name: "Sigil of the Wizard", type: "damage", power: "Pushes enemies + ice root for 1.5s.", debuff: "CC push + root", cooldown: 60, set: "None", source: "Vault of the Nine (Wizard)", image: "images/artifacts/Icon_Inventory_Artifacts_Class_Control.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Strike","value":450},{"stat":"Control Resist","value":450}] },
    { name: "Sigil of the Ranger", type: "damage", power: "Rain of arrows + bramble thorns AoE.", debuff: "None", cooldown: 60, set: "None", source: "Vault of the Nine (Ranger)", image: "images/artifacts/Icon_Inventory_Artifacts_Class_Hunter.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Accuracy","value":450}] },
    { name: "Sigil of the Rogue", type: "damage", power: "Teleport to enemy within 40'. Cone knife spray.", debuff: "None", cooldown: 60, set: "None", source: "Vault of the Nine (Rogue)", image: "images/artifacts/Icon_Inventory_Artifacts_Class_Trickster.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Strike","value":450},{"stat":"Combat Advantage","value":450},{"stat":"Deflect","value":450}] },
    // -- Dragon Hearts --
    { name: "Heart of the Blue Dragon", type: "damage", power: "Lightning line to 7 enemies + chain. +2,550 Defense 8s.", debuff: "None", cooldown: 60, set: "Hearts of the Dragons", source: "Dragon content", image: "images/artifacts/Icon_Inventory_Artifacts_Blue_Dragon_Heart.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Strike","value":450},{"stat":"Combat Advantage","value":450},{"stat":"Accuracy","value":450}] },
    { name: "Heart of the Red Dragon", type: "damage", power: "AoE fire to 7 enemies + fire DoT 4s. +2,550 Defense 8s.", debuff: "None", cooldown: 60, set: "Hearts of the Dragons", source: "Dragon content", image: "images/artifacts/Icon_Inventory_Artifacts_Red_Dragon_Heart.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Defense","value":450},{"stat":"Awareness","value":450}] },
    { name: "Heart of the Green Dragon", type: "damage", power: "Poison AoE + poison cloud DoT 13s. +2,550 Defense 8s.", debuff: "None", cooldown: 60, set: "Hearts of the Dragons", source: "Dragon content", image: "images/artifacts/Icon_Inventory_Artifacts_Green_Dragon_Heart.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Awareness","value":450},{"stat":"Deflect","value":450},{"stat":"Incoming Healing","value":450}] },
    { name: "Heart of the White Dragon", type: "damage", power: "Cone cold to 7 enemies + slow 6.3s. +2,550 Defense 8s.", debuff: "None", cooldown: 60, set: "Hearts of the Dragons", source: "Dragon content", image: "images/artifacts/Icon_Inventory_Artifacts_White_Dragon_Heart.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Accuracy","value":450},{"stat":"Defense","value":450}] },
    // -- Elemental Symbols --
    { name: "Symbol of Air", type: "utility", power: "Teleport 40' + AoE damage. If no enemies: +30% movement speed 5s.", debuff: "Teleport / escape", cooldown: 60, set: "None", source: "Elemental Evil", image: "images/artifacts/Icon_Inventory_Artifacts_Symbolofair.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Accuracy","value":450},{"stat":"Critical Avoidance","value":450}] },
    { name: "Symbol of Fire", type: "damage", power: "Spreading fire on target. Activate again for AoE fire burst.", debuff: "None", cooldown: 60, set: "None", source: "Elemental Evil", image: "images/artifacts/Icon_Inventory_Artifacts_Symboloffire.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Accuracy","value":450},{"stat":"Defense","value":450}] },
    { name: "Symbol of Water", type: "damage", power: "Maelstrom pulls enemies in. Damage over 5s + final burst.", debuff: "None", cooldown: 60, set: "None", source: "Elemental Evil", image: "images/artifacts/Icon_Inventory_Artifacts_Symbolofwater.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Strike","value":450},{"stat":"Deflect","value":450}] },
    { name: "Symbol of Earth", type: "damage", power: "Earthmote drops on target. Knockback + ring damage.", debuff: "None", cooldown: 60, set: "None", source: "Elemental Evil", image: "images/artifacts/Icon_Inventory_Artifacts_Symbolofearth.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Critical Severity","value":450},{"stat":"Control Resist","value":450}] },
    // -- Misc --
    { name: "Shard of Valindra's Crown", type: "utility", power: "Two swipes of Valindra's hand. Immune to damage and control while casting.", debuff: "Self-immunity during cast", cooldown: 60, set: "None", source: "Dungeon content", image: "images/artifacts/Icon_Inventory_Artifacts_ShardOfValindrasCrown.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Control Bonus","value":450}] },
    { name: "Fragmented Key of Stars", type: "damage", power: "Summons Far Realm Horror dealing AoE damage + knockback.", debuff: "None", cooldown: 60, set: "None", source: "Cloaked Ascendancy", image: "images/artifacts/Icon_Inventory_Artifacts_Keyofstars.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Severity","value":450},{"stat":"Critical Strike","value":450}] },
    { name: "Kessell's Spheres of Annihilation", type: "damage", power: "8 spheres orbit damaging enemies on contact.", debuff: "None", cooldown: 60, set: "None", source: "Kessell's Retreat", image: "images/artifacts/Icon_Inventory_Artifacts_Sphereofannihilation.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Severity","value":450},{"stat":"Combat Advantage","value":450}] },
    { name: "Black Ice Beholder", type: "damage", power: "Illusory Beholder moves forward attacking. Explodes after 10s.", debuff: "None", cooldown: 60, set: "None", source: "Icewind Dale", image: "images/artifacts/Icon_Inventory_Artifacts_BlackIce_Beholder.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Severity","value":450},{"stat":"Combat Advantage","value":450},{"stat":"Accuracy","value":450}] },
    { name: "Bruenor's Helm", type: "utility", power: "Summons Throne. Allies gain +378 Defense and Crit Avoidance. Foes slowed 25% (demons 50%).", debuff: "Ally defense + slow", cooldown: 60, set: "None", source: "Promotional", image: "images/artifacts/Icon_Inventory_Artifacts_BruenorsHelm.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Defense","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Incoming Healing","value":450}] },
    { name: "Skull Lord Staff", type: "damage", power: "Tri-point attack. On kill: chance to summon skeleton for 15s.", debuff: "None", cooldown: 60, set: "None", source: "Dungeon content", image: "images/artifacts/Icon_Inventory_Artifacts_Gravemasterstaff.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Defense","value":450},{"stat":"Gold Bonus","value":450}] },
    { name: "Memories (Redeemed)", type: "utility", power: "Grants 3% Incoming Healing. When healed: +5% Power for 6s.", debuff: "Healing + Power buff", cooldown: 60, set: "Redeemed Set", source: "Redeemed Citadel event" },
    // -- Storyteller Journals --
    { name: "Flayed Storyteller's Journal", type: "personal", power: "25' AoE + stun 3s. +5% damage after 15s. Summons intellect devourer. +10% Deflect 20s.", debuff: "5% personal damage + Deflect", cooldown: 60, set: "Storyteller's Journals", source: "Zen Market / Tales of Old", image: "images/artifacts/Icon_Inventory_Artifacts_Storytellers_Journal_Vault.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":450},{"stat":"Accuracy","value":450},{"stat":"Critical Avoidance","value":450}] },
    { name: "Envenomed Storyteller's Journal", type: "personal", power: "25' AoE + stun 3s. +5% weapon damage per stack. +5% damage. Generates 20 AP/s for 15s.", debuff: "5% damage + AP gen", cooldown: 60, set: "Storyteller's Journals", source: "Zen Market / Tales of Old", image: "images/artifacts/Icon_Inventory_Artifacts_Storytellers_Journal_Envenomed.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Power","value":450},{"stat":"Critical Strike","value":450},{"stat":"Combat Advantage","value":450},{"stat":"Defense","value":450}] },
    { name: "Darkened Storyteller's Journal", type: "personal", power: "25' AoE + stun 3.2s. +5% necrotic weapon damage per stack. -5,000 enemy Armor Pen.", debuff: "5% necrotic damage + enemy ArP shred", cooldown: 60, set: "Storyteller's Journals", source: "Zen Market / Tales of Old", image: "images/artifacts/Icon_Inventory_Artifacts_Storytellers_Journal_Idris.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Power","value":450},{"stat":"Awareness","value":450},{"stat":"Deflect","value":450},{"stat":"Forte","value":450}] },
    // -- Newly discovered artifacts --
    { name: "Demogorgon's Reach", type: "debuff", power: "Summons 6 tentacles over 6s. Struck foes gain Rotting for 6s: +3% damage taken per stack, -5% incoming healing per stack. Stacks up to 6x (max 18% more damage taken).", debuff: "18% stacking group debuff", cooldown: 60, set: "None", source: "Demogorgon (Master)", image: "images/artifacts/Icon_Inventory_Artifacts_Demogorgon_Revamp.webp", itemLevel: 1200, combinedRating: 1020, stats: [{"stat":"Max HP","value":3600},{"stat":"Power","value":900},{"stat":"Forte","value":900}] },
    { name: "Dragonbone Blades", type: "debuff", power: "Throws blades dealing Necrotic damage + DoT every 1s for 10s. Enemies take 12% more damage and deal 12% less damage.", debuff: "12% more damage taken + 12% less damage dealt", cooldown: 60, set: "None", source: "Lockbox", image: "images/artifacts/Icon_Inventory_Artifact_Dragonboneblades.webp", itemLevel: 1200, combinedRating: 1020, stats: [{"stat":"Critical Severity","value":900},{"stat":"Critical Strike","value":900},{"stat":"Accuracy","value":900}] },
    { name: "Mythallar Fragment", type: "debuff", power: "Arcane blast, stuns target. Target's damage resistance lowered by 15% for duration.", debuff: "15% damage resistance reduction", cooldown: 60, set: "None", source: "Dragonbone Vale Campaign", image: "images/artifacts/Icon_Inventory_Artifact_M22_Zone.webp", itemLevel: 1200, combinedRating: 960, stats: [{"stat":"Combat Advantage","value":1800},{"stat":"Accuracy","value":900}] },
    { name: "Jewel of the North", type: "debuff", power: "Lunge forward dealing line damage. Targets take 10% more damage for 10s. Passive: 15% more/less threat based on role.", debuff: "10% more damage taken", cooldown: 60, set: "None", source: "Echoes of Prophecy Battle Pass", image: "images/artifacts/Icon_Inventory_Artifacts_NorthernJewel.webp", itemLevel: 1200, combinedRating: 1020, stats: [{"stat":"Power","value":900},{"stat":"Critical Strike","value":900},{"stat":"Defense","value":900}] },
    { name: "Tentacle Rod", type: "debuff", power: "Damages 4 times, dazes 6.1s. Enemies lose 5% Movement Speed, 5% Awareness, take 5% more damage from party for 10s.", debuff: "5% more damage + stat shred", cooldown: 60, set: "None", source: "Lockbox", image: "images/artifacts/Icon_Inventory_Artifact_M24_Dungeon_Tentacle.webp", itemLevel: 1200, combinedRating: 1020, stats: [{"stat":"Critical Severity","value":900},{"stat":"Combat Advantage","value":1800}] },
    { name: "Neverwinter's Standard", type: "debuff", power: "Banner for 15s. Allies gain 5% Recharge Speed. Foes take 5% more damage.", debuff: "5% more damage + ally Recharge Speed", cooldown: 60, set: "None", source: "Promotional", image: "images/artifacts/Icon_Inventory_Artifacts_Neverwinter.webp", itemLevel: 1200, combinedRating: 1020, stats: [{"stat":"Power","value":900},{"stat":"Critical Severity","value":900},{"stat":"Awareness","value":900}] },
    { name: "Tome of Ascendance", type: "utility", power: "4 random spell glyphs on ground. Allies consume for 15s buff: Fey = 10% less damage taken + 15% Healing/Speed. Illusion = Stealth + 15% enemy Defense reduction. Aboleth/Fireforged = damage bonuses.", debuff: "10-15% buffs (RNG-dependent)", cooldown: 60, set: "None", source: "Many-Starred Lockbox", image: "images/artifacts/Icon_Inventory_Artifacts_Tomeofascendance.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Power","value":450},{"stat":"Defense","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Deflect","value":450}] },
    { name: "Assassin's Dice", type: "debuff", power: "Throw dice at enemy. Target marked for 15s: -5% Critical Chance, -5% Critical Avoidance, -5% Deflect Severity.", debuff: "-5% Crit/CA/Deflect Sev on target", cooldown: 60, set: "None", source: "Lockbox", image: "images/artifacts/Icon_Inventory_Artifact_M24_Zone_Assassin.webp", itemLevel: 1200, combinedRating: 1020, stats: [{"stat":"Power","value":1800},{"stat":"Accuracy","value":900}] },
    { name: "Empowered Illusionist's Mask", type: "personal", power: "Gaze deals damage, polymorphs enemies. You deal up to 15% more damage against transformed targets for up to 15s.", debuff: "15% personal damage vs transformed", cooldown: 60, set: "None", source: "Masquerade of Liars event", image: "images/artifacts/Icon_Inventory_Artifacts_IllusionistsMask_Empowered.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Accuracy","value":450},{"stat":"Awareness","value":450}] },
    { name: "Golden Memories", type: "personal", power: "Radiant AoE in 20'. +3% damage per enemy hit for 6s, stacks up to 5x (max 15% self-damage).", debuff: "15% personal damage ramp", cooldown: 60, set: "None", source: "Promotional", image: "images/artifacts/Icon_Inventory_Artifact_Redeemed.webp", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":900},{"stat":"Critical Strike","value":450}] },
    { name: "Alaric's Artillery Beacon", type: "debuff", power: "AoE damage (50' range, 20' radius), stun up to 4s. Enemies take up to 5% more damage for 10s.", debuff: "5% more damage taken + stun", cooldown: 60, set: "None", source: "First Contact Battle Pass", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Combat Advantage","value":1688},{"stat":"Accuracy","value":1688}] },
    { name: "Tiamat's Arcane Globe", type: "tank", power: "Restores 75 stamina. Passive: when stamina below 15%, 8% damage reduction + 8% Critical Avoidance for 10s (20s CD).", debuff: "8% damage reduction (conditional)", cooldown: 60, set: "Tiamat's Prized Possessions", source: "Rise of Tiamat (Master)", image: "images/artifacts/Icon_Inventory_Artifact_M23_Trial_Tiamat.webp", itemLevel: 1200, combinedRating: 960, stats: [{"stat":"Max HP","value":3600},{"stat":"Awareness","value":900},{"stat":"Forte","value":1800}] },
    { name: "Tactician's Banner", type: "utility", power: "Banner for 30s. Allies gain 25% Movement Speed and 5% faster AP gain. Foes gain AP 5% slower.", debuff: "25% ally Movement Speed + 5% AP Gain", cooldown: 60, set: "None", source: "PVP (40k Glory)", image: "images/artifacts/Icon_Inventory_Artifacts_TacticianBanner.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Strike","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Awareness","value":450}] },
    { name: "Champion's Banner", type: "tank", power: "Banner for 30s. Allies gain 5% Incoming Healing and 2,500 Accuracy. Foes deal 5% less damage.", debuff: "5% less enemy damage + ally heals", cooldown: 60, set: "None", source: "PVP (40k Glory)", image: "images/artifacts/Icon_Inventory_Artifacts_Championsbanner.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Defense","value":450},{"stat":"Stamina Regen","value":15}] },
    { name: "Siegebreaker's Banner", type: "utility", power: "Banner for 30s. Allies gain 2,500 Crit Avoidance, 2,500 Armor Penetration, 5% Recharge Speed.", debuff: "Ally stat buffs (30s)", cooldown: 60, set: "None", source: "Siege of Neverwinter", image: "images/artifacts/Icon_Inventory_Artifacts_Siegebreaker.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Severity","value":450},{"stat":"Combat Advantage","value":450}] },
    { name: "Red Dragon's Mark", type: "personal", power: "Fireball + knockdown. Passive: on Encounter use, gain 2.5% Combat Advantage + 5% Movement Speed for 5s, stacks 3x (7.5% CA).", debuff: "7.5% CA passive (stacking)", cooldown: 60, set: "Aggressive Alacrity", source: "Dragonslayer Campaign", image: "images/artifacts/Icon_Inventory_Artifact_Dragonhunt_Red.webp", itemLevel: 1200, combinedRating: 960, stats: [{"stat":"Power","value":1800},{"stat":"Defense","value":900},{"stat":"Forte","value":900}] },
    { name: "Black Dragon's Mark", type: "debuff", power: "Acid ball dealing damage. Decreases target damage resistance by 10%.", debuff: "10% damage resistance reduction", cooldown: 60, set: "None", source: "Dragonslayer Campaign", image: "images/artifacts/Icon_Inventory_Artifact_Dragonhunt_Black.webp", itemLevel: 1200, combinedRating: 960, stats: [{"stat":"Max HP","value":3600},{"stat":"Critical Avoidance","value":1800},{"stat":"Awareness","value":900}] },
    { name: "White Dragon's Mark", type: "utility", power: "Cold ball + slow. Passive: on Encounter use, gain 2.5% Critical Strike + 5% Incoming Healing for 5s, stacks 3x.", debuff: "7.5% Crit Strike passive", cooldown: 60, set: "Celestial Alacrity", source: "Dragonslayer Campaign", image: "images/artifacts/Icon_Inventory_Artifact_Dragonhunt_White.webp", itemLevel: 1200, combinedRating: 960, stats: [{"stat":"Max HP","value":3600},{"stat":"Combat Advantage","value":900},{"stat":"Control Bonus","value":1800}] },
    { name: "Green Dragon's Mark", type: "personal", power: "Poison ball + DoT. Passive: on Encounter use, gain 2.5% Crit Severity + 5% Movement Speed for 5s, stacks 3x (7.5% Crit Sev).", debuff: "7.5% Crit Severity passive", cooldown: 60, set: "Insightful Alacrity", source: "Dragonslayer Campaign", image: "images/artifacts/Icon_Inventory_Artifact_Dragonhunt_Green.webp", itemLevel: 1200, combinedRating: 960, stats: [{"stat":"Defense","value":1800},{"stat":"Deflect","value":900},{"stat":"Forte","value":900}] },
    { name: "Blue Dragon's Mark", type: "personal", power: "Lightning ball + stun. Passive: on Encounter use, gain stat buff for 5s, stacks 3x.", debuff: "Stacking passive buff", cooldown: 60, set: "Vanguard's Alacrity", source: "Dragonslayer Campaign", image: "images/artifacts/Icon_Inventory_Artifact_Dragonhunt_Blue.webp", itemLevel: 1200, combinedRating: 960, stats: [{"stat":"Critical Severity","value":900},{"stat":"Critical Strike","value":1800},{"stat":"Deflect","value":900}] },
    { name: "Sigil of the Nine", type: "debuff", power: "Spirits of the Nine attack, dealing damage + root 4.5s. Allies' damage increased 3% for 9s.", debuff: "3% ally damage buff", cooldown: 60, set: "None", source: "Lockbox", image: "images/artifacts/Icon_Inventory_Artifacts_Sigilofthenine.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Defense","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Deflect","value":450}] },
    { name: "Thayan Book of the Dead", type: "personal", power: "Summons 3 undead + root 2s + necrotic DoT. Passive: on dodge/block/sprint, +5% Power + 5% Movement Speed for 10s (45s CD).", debuff: "5% Power passive", cooldown: 60, set: "Set of the Dead", source: "Dread Ring", image: "images/artifacts/Icon_Inventory_Artifacts_ThayanBookOfTheDead.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Critical Severity","value":450},{"stat":"Critical Strike","value":450},{"stat":"Awareness","value":450}] },
    { name: "Emblem of the Seldarine", type: "utility", power: "Buffs allies with Seldarine's Blessing for 15s: healed for 4,816 HP every time hit (1/s max).", debuff: "Party HoT on hit", cooldown: 60, set: "Seldarine Set", source: "Malabog's Castle", image: "images/artifacts/Icon_Inventory_Artifacts_Emblemoftheseldarine.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Defense","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Forte","value":450}] },
    { name: "Belial's Portal Stone", type: "damage", power: "Summons portal that generates threat. Explodes after 20s for massive AoE damage.", debuff: "None", cooldown: 60, set: "None", source: "Lockbox", image: "images/artifacts/Icon_Inventory_Artifacts_Belialsportalstone.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Control Bonus","value":450}] },
    { name: "Sphere of Black Ice", type: "damage", power: "Roots target 3s + damage/s. After 3s, explodes dealing AoE damage.", debuff: "Root + AoE", cooldown: 60, set: "None", source: "Frozen Crystal Lockbox", image: "images/artifacts/Icon_Inventory_Artifacts_Blackice_Sphere.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Accuracy","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Control Bonus","value":450}] },
    { name: "Champion's Battle Horn", type: "tank", power: "Grants 5,494 Temp HP for 8s + 50% Run Speed for 3s. When taking damage, CD reduced by 1s.", debuff: "Temp HP + speed burst", cooldown: 60, set: "None", source: "Siege of Neverwinter", image: "images/artifacts/Icons_Inventory_Event_Siege_Championsbattlehorn_01.webp" },
    { name: "Beacon of Simril", type: "utility", power: "6 lanterns fall over 15s. Allies catch for heal. At 6 stacks: gain Power buff for 30s.", debuff: "Party heal + Power buff", cooldown: 60, set: "None", source: "Winter Festival", image: "images/artifacts/Icon_Inventory_Artifacts_Winterlantern.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Awareness","value":450}] },
    { name: "Flask of Brewing", type: "damage", power: "Throws burning brew at 60' range, AoE puddle for 10-15s. Passive: at combat start +1,000 Power + 5% Movement Speed for 10s.", debuff: "None", cooldown: 60, set: "None", source: "Festival event", image: "images/artifacts/Icon_Inventory_Artifacts_Acqinc.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Critical Severity","value":450},{"stat":"Critical Avoidance","value":450}] },
    { name: "Illusionist's Mask", type: "utility", power: "Become illusion of random monster for 5s, significantly reducing threat.", debuff: "Threat drop", cooldown: 60, set: "None", source: "Masquerade of Liars", image: "images/artifacts/Icon_Inventory_Artifacts_Illusionistsmask.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Accuracy","value":450},{"stat":"Deflect","value":450},{"stat":"Stamina Regen","value":15}] },
    { name: "Crown of the Undead", type: "utility", power: "When using Daily, pulls enemies within 20' towards you, stuns undead 3s.", debuff: "Pull + undead stun", cooldown: 30, set: "None", source: "Dread Ring", image: "images/artifacts/Inventory_Feet_M14_Hunt_Chase_Consort_Head.webp" },
    { name: "Manticore Talon", type: "damage", power: "Leap to location, summon avalanche dealing damage + pushback over 4s.", debuff: "None", cooldown: 60, set: "None", source: "Manticore content", image: "images/artifacts/Icon_Inventory_Artifacts_Manticoretalon.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Critical Strike","value":450},{"stat":"Control Resist","value":450}] },
    { name: "Rod of Imperial Restraint", type: "utility", power: "Hold target 4s (2s vs players). Creates 3 hold zones.", debuff: "CC hold", cooldown: 60, set: "None", source: "Stronghold Siege", image: "images/artifacts/Icon_Inventory_Artifacts_Dragoncultist.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Accuracy","value":450},{"stat":"Critical Avoidance","value":450},{"stat":"Control Bonus","value":450}] },
    { name: "Siege Master's War Horn", type: "damage", power: "Calls catapult bombardment on target area. Each teammate with one adds a catapult (max 5).", debuff: "None", cooldown: 60, set: "None", source: "Siege of Neverwinter", image: "images/artifacts/Icon_Inventory_Artifacts_Siege_Masters_War_Horn.webp", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Max HP","value":1800},{"stat":"Power","value":450},{"stat":"Critical Avoidance","value":450}] },
    // -- Mod 26+ artifacts --
    { name: "Demon Skull", type: "debuff", power: "Summons 3 imps that swarm enemies. On death they erupt, each dealing AoE damage. Enemies take 5% more damage and lose 5% Accuracy for 10s.", debuff: "5% more damage taken + 5% Accuracy reduction", cooldown: 60, set: "None", source: "Demonweb Pits (Mod 26)", image: "images/artifacts/demon_skull.webp", itemLevel: 2600, combinedRating: 2600, stats: [{"stat":"Power","value":2184},{"stat":"Critical Severity","value":1825},{"stat":"Combat Advantage","value":2496}] },
    { name: "Nightflame Censer", type: "debuff", power: "Scorches enemies with black flames dealing AoE damage. Burned foes take DoT every 1s for 10s. Targets deal 11.9% less damage and take 12.5% more damage from all sources for 10s.", debuff: "12.5% more damage taken + 11.9% less damage dealt", cooldown: 60, set: "None", source: "Demonweb Pits (Mod 26)", image: "images/artifacts/nightflame_censer.webp", itemLevel: 2600, combinedRating: 2080, stats: [{"stat":"Power","value":2184},{"stat":"Forte","value":3510},{"stat":"Combat Advantage","value":2496}] },
    { name: "Marilith Mask", type: "debuff", power: "Unleashes laser beams dealing damage to single or multiple enemies. Enemies struck take 7.5% more damage for 10s.", debuff: "7.5% more damage taken", cooldown: 40, set: "Marilith Strike", source: "Demonweb Pits (Mod 26)", image: "images/artifacts/marilith_mask.webp", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Critical Severity","value":1125},{"stat":"Combat Advantage","value":1125},{"stat":"Accuracy","value":1125}] },
    { name: "Xeleth's Blast Scepter", type: "debuff", power: "Hits enemy with an arcane blast, stunning and damaging it. Target's damage resistance lowered by 15%.", debuff: "15% damage resistance reduction", cooldown: 60, set: "Astral Dash", source: "Demonweb Pits (Mod 26)", itemLevel: 1500, combinedRating: 1200, stats: [{"stat":"Max HP","value":4500},{"stat":"Power","value":2250},{"stat":"Critical Strike","value":1125}] },
    // -- Newly added (intake May 2026, sources/sets need verification) --
    { name: "Arcturia's Resonating Music Box", type: "personal", power: "Stronger Music Box variant. Summons 2 mimics dealing AoE damage. Consumes minions on hit.", debuff: "None (set bonus is the value)", cooldown: 60, set: "Apprentices' Spoils", source: "Zok boxes (Undermountain) — mythic refinement upgrade", itemLevel: 1800, combinedRating: 1440, stats: [{"stat":"Power","value":1350},{"stat":"Critical Severity","value":1350},{"stat":"Combat Advantage","value":2700}] },
    { name: "Arma-Egg-On", type: "damage", power: "Deals AoE damage to enemies. Empowered during Fowl event seasons.", debuff: "None", cooldown: 60, set: "None", source: "Fowl event (seasonal)", itemLevel: 2600, combinedRating: 2080, stats: [{"stat":"Critical Severity","value":2340},{"stat":"Accuracy","value":2535},{"stat":"Combat Advantage","value":1560}] },
    { name: "Assassin's Knife", type: "personal", power: "Throws knife for damage + poison DoT (10s). Self gains +9% Critical Strike for 10s.", debuff: "+9% Crit Strike (self)", cooldown: 60, set: "None", source: "? (needs verification)", itemLevel: 2000, combinedRating: 2000, stats: [{"stat":"Critical Severity","value":1800},{"stat":"Accuracy","value":1950},{"stat":"Combat Advantage","value":1200}] },
    { name: "Astral Seed Tendril", type: "utility", power: "Arcane AoE damage + heals self per target hit. Additional DoT/HoT over 12s. Doubled in Wildspace.", debuff: "Self heal scaling with targets", cooldown: 60, set: "None", source: "Wildspace (Mod 28 Spelljammer)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Power","value":1125},{"stat":"Accuracy","value":1125},{"stat":"Deflect","value":1125}] },
    { name: "Beacon of Meteor Swarm", type: "debuff", power: "Storm of 6 meteors hits target area. Stuns 4s + DoT. +10% damage taken for 10s.", debuff: "10% more damage taken + stun", cooldown: 60, set: "None", source: "Doomspace Lockbox (Mod 28)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Critical Severity","value":1125},{"stat":"Critical Strike","value":1125},{"stat":"Combat Advantage","value":1125}] },
    { name: "Beacon of the Astral Sea", type: "utility", power: "Avatar of Light: +20% Outgoing Healing, +10% Damage Resistance for 10s. Allies healed gain +5% damage for 10s.", debuff: "Healer ramp + ally damage buff", cooldown: 60, set: "None", source: "Wildspace / Spelljammer (Mod 28)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Defense","value":1125},{"stat":"Forte","value":1125},{"stat":"Incoming Healing","value":1125}] },
    { name: "Bloodbrass Pistol", type: "debuff", power: "Fires Blunderbuss dealing damage. Target takes +6% more damage for 10s (boosted in Pirates' Skyhold).", debuff: "6% more damage taken (10s)", cooldown: 60, set: "None", source: "Pirates' Skyhold (Mod 30)", itemLevel: 2000, combinedRating: 2000, stats: [{"stat":"Critical Severity","value":1500},{"stat":"Combat Advantage","value":1500},{"stat":"Accuracy","value":1500}] },
    { name: "Broken Halo", type: "debuff", power: "Burst of light dealing AoE damage. Stuns lesser enemies 1.3s. +9% damage taken for 10s.", debuff: "9% more damage taken + stun", cooldown: 60, set: "None", source: "? (needs verification)", itemLevel: 2600, combinedRating: 2210, stats: [{"stat":"Critical Avoidance","value":1950},{"stat":"Deflect","value":1950},{"stat":"Deflect Severity","value":1950}] },
    { name: "Crimson Calamity", type: "debuff", power: "Self-damage to gain shield + AoE physical damage. Targets deal -10% damage for 10s.", debuff: "10% less enemy damage (10s)", cooldown: 60, set: "None", source: "Crimson Horizon Battle Pass (Premium Track, Mod 30)", itemLevel: 2600, combinedRating: 2600, stats: [{"stat":"Defense","value":1365},{"stat":"Deflect Severity","value":2925},{"stat":"Combat Advantage","value":1560},{"stat":"Stamina Regen","value":15}] },
    { name: "Crystal of Soul's Flight", type: "debuff", power: "Target takes +10% damage from all sources, +15% damage from your attacks for 10s.", debuff: "10% group + 15% personal damage taken", cooldown: 60, set: "None", source: "Shadowy Flight Lockbox", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Power","value":1125},{"stat":"Combat Advantage","value":1125},{"stat":"Accuracy","value":1125}] },
    { name: "Deck of a Few Things", type: "utility", power: "Draws a random card with various RNG effects.", debuff: "RNG", cooldown: 60, set: "None", source: "? (needs verification — likely Tarokka-related event)", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Strike","value":450},{"stat":"Critical Avoidance","value":450}] },
    { name: "Draconic Essence", type: "damage", power: "Fire + Lightning frontal damage. Targets suffer Poison DoT for 6s + Acid burst on expiration.", debuff: "None", cooldown: 60, set: "None", source: "Dragonslayer Campaign (Mod 23)?", itemLevel: 1200, combinedRating: 1020, stats: [{"stat":"Power","value":900},{"stat":"Critical Strike","value":900},{"stat":"Control Resist","value":900}] },
    { name: "Dragonbone Wand", type: "debuff", power: "Force damage + 3s stun. Enemies take +4% more damage from you for 6s.", debuff: "4% more damage taken (personal, 6s)", cooldown: 60, set: "None", source: "Dragonbone Vale Campaign (Mod 22)?", itemLevel: 1200, combinedRating: 1020, stats: [{"stat":"Max HP","value":3600},{"stat":"Accuracy","value":900},{"stat":"Defense","value":900}] },
    { name: "Eye of Odran", type: "personal", power: "Illithid Sight: -20% Max HP for 10s. Self gains +7.5% AP Gain, Stamina Regen, and Movement Speed for 10s.", debuff: "Self mobility/AP buff (HP cost)", cooldown: 60, set: "Attuned Eye of Odran", source: "Menzoberranzan Campaign (Mod 25) — campaign shop", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Combat Advantage","value":1125},{"stat":"Accuracy","value":1125},{"stat":"Control Resist","value":1125}] },
    { name: "Globe of the Third Eye", type: "utility", power: "Effect details unknown — needs verification.", debuff: "?", cooldown: 60, set: "None", source: "? (needs verification — older Savras/Tyranny of Dragons era)", itemLevel: 310, combinedRating: 212, stats: [{"stat":"Max HP","value":750},{"stat":"Critical Strike","value":188},{"stat":"Control Resist","value":188}] },
    { name: "Grace of Pelor", type: "tank", power: "Self + ally barrier: +10% Defense, +8% Base Damage Boost, Shield up to 300k HP (cap 15% target HP). 15s.", debuff: "Large shield + ally buffs", cooldown: 60, set: "None", source: "Pirates' Skyhold lockbox (Mod 30)", itemLevel: 2000, combinedRating: 1600, stats: [{"stat":"Power","value":1680},{"stat":"Forte","value":2700},{"stat":"Defense","value":1680}] },
    { name: "Heart of the Volcano", type: "debuff", power: "Fire line damage. Targets take +10% damage from all sources, you take 10% less damage. 10s.", debuff: "10% more damage taken + 10% self DR", cooldown: 60, set: "None", source: "Foxfire Lockbox (Mod 29 Mountain of Flame)", itemLevel: 1800, combinedRating: 1530, stats: [{"stat":"Critical Avoidance","value":1350},{"stat":"Awareness","value":1350},{"stat":"Stamina Regen","value":15}] },
    { name: "Imbued Staff of Flowers", type: "utility", power: "Poison DoT + flower wreath. Enemies in wreath -25% Movement. Allies +6% Power and Crit Strike for 10s.", debuff: "Ally Power + Crit buff zone (10s)", cooldown: 60, set: "Enchanted Thumb", source: "Mythic refinement upgrade of Staff of Flowers", itemLevel: 1800, combinedRating: 1440, stats: [{"stat":"Power","value":2700},{"stat":"Critical Strike","value":1350},{"stat":"Awareness","value":1350}] },
    { name: "Jewel of the Caldera", type: "debuff", power: "Lunge forward dealing line damage. Targets take +10% damage for 10s.", debuff: "10% more damage taken (lunge)", cooldown: 60, set: "None", source: "Mountain of Flame (Mod 29)", itemLevel: 1800, combinedRating: 1530, stats: [{"stat":"Power","value":1350},{"stat":"Critical Strike","value":1350},{"stat":"Defense","value":1350}] },
    { name: "Marco's Mystic Marker", type: "debuff", power: "Rapid arcane attacks. Target takes +10% damage from all sources for 10s.", debuff: "10% more damage taken (10s)", cooldown: 60, set: "None", source: "Starlight Armaments Lockbox", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Critical Severity","value":1125},{"stat":"Accuracy","value":2250}] },
    { name: "Mystic Bolt", type: "debuff", power: "Bolts deal AoE damage. Creates magical pool that lowers enemy Awareness.", debuff: "Awareness shred (value TBD)", cooldown: 60, set: "None", source: "Demonweb Pits Campaign (Mod 26)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Power","value":1125},{"stat":"Accuracy","value":1125},{"stat":"Deflect","value":1125}] },
    { name: "Portable Spelljammer Detector", type: "debuff", power: "Disrupts spelljamming in 25' radius. Enemies take +12% damage for 10s. Self gains +7.5% Crit Severity for 10s.", debuff: "12% more damage taken (10s)", cooldown: 60, set: "None", source: "Wildspace / Spelljammer (Mod 28)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Power","value":1125},{"stat":"Accuracy","value":1125},{"stat":"Deflect","value":1125}] },
    { name: "Realm Engine Core", type: "debuff", power: "Heavy single-target damage. Target takes +7.5% damage for 10s. Self shield = 15% of HP for 30s.", debuff: "7.5% more damage taken + self shield", cooldown: 60, set: "Rune of the Underdark", source: "Demonweb Pits Campaign (Mod 26)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Critical Avoidance","value":1688},{"stat":"Awareness","value":1688}] },
    { name: "Repurposed Phylactory", type: "utility", power: "Necrotic AoE damage. Heals you for 108,265 over 6s per enemy hit.", debuff: "Self heal scaling with targets", cooldown: 60, set: "Beyond Death", source: "Sharandar (Mod 22)", itemLevel: 1200, combinedRating: 1020, stats: [{"stat":"Max HP","value":3600},{"stat":"Critical Severity","value":900},{"stat":"Combat Advantage","value":900}] },
    { name: "Ring of Fowl Weather", type: "damage", power: "Summons tornado of chickens, pulling enemies in and dealing damage.", debuff: "None (cosmetic event)", cooldown: 60, set: "None", source: "April Fowls event", itemLevel: 600, combinedRating: 480, stats: [{"stat":"Combat Advantage","value":450},{"stat":"Defense","value":900},{"stat":"Awareness","value":450}] },
    { name: "Rod of Pain", type: "personal", power: "Psychic AoE damage + 8s DoT. Self gains +7.5% Crit Strike and Awareness for 10s. Doubled in Underdark.", debuff: "+7.5% personal Crit/Awareness", cooldown: 60, set: "None", source: "Demonweb Pits Campaign (Mod 26)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Power","value":1125},{"stat":"Critical Severity","value":1125},{"stat":"Combat Advantage","value":1125}] },
    { name: "Scintillating Symbol of Air", type: "utility", power: "Stronger Symbol of Air: 40' teleport + AoE damage. If miss: +30% movement speed 5s.", debuff: "Teleport / escape", cooldown: 60, set: "None", source: "Defense of the Moondancer trial (Mod 27)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Power","value":1125},{"stat":"Accuracy","value":1125},{"stat":"Critical Avoidance","value":1125}] },
    { name: "Scintillating Symbol of Earth", type: "damage", power: "Stronger Symbol of Earth: earthmote drop with knockback + ring damage.", debuff: "None", cooldown: 60, set: "None", source: "Defense of the Moondancer trial (Mod 27)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Max HP","value":4500},{"stat":"Critical Severity","value":1125},{"stat":"Control Resist","value":1125}] },
    { name: "Scintillating Symbol of Fire", type: "damage", power: "Stronger Symbol of Fire: spreading fire + AoE explosion on second activation.", debuff: "None", cooldown: 60, set: "None", source: "Defense of the Moondancer trial (Mod 27)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Power","value":1125},{"stat":"Accuracy","value":1125},{"stat":"Defense","value":1125}] },
    { name: "Scintillating Symbol of Water", type: "damage", power: "Stronger Symbol of Water: maelstrom pulls + DoT + final burst.", debuff: "None", cooldown: 60, set: "None", source: "Defense of the Moondancer trial (Mod 27)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Critical Strike","value":1125},{"stat":"Deflect","value":1125}] },
    { name: "Sealing Parchment", type: "debuff", power: "Self +7.5% Deflect/Deflect Severity for 10s. Initial enemies take +7.5% damage from all sources + DoT for 10s.", debuff: "7.5% more damage taken + self Deflect", cooldown: 60, set: "None", source: "Pirates' Skyhold (Mod 30)", itemLevel: 2600, combinedRating: 2600, stats: [{"stat":"Defense","value":1365},{"stat":"Combat Advantage","value":1560},{"stat":"Awareness","value":1560},{"stat":"Stamina Regen","value":15}] },
    { name: "Searing Conduit of Magma", type: "personal", power: "Self +22% Base Damage Boost for 10s. Attackers burn for damage (1/2s per enemy).", debuff: "+22% personal damage + retaliation", cooldown: 60, set: "None", source: "Mountain of Flame (Mod 29)", itemLevel: 1800, combinedRating: 1530, stats: [{"stat":"Power","value":1350},{"stat":"Combat Advantage","value":1350},{"stat":"Defense","value":1350}] },
    { name: "Sigil of the Bard", type: "utility", power: "Radiant damage to 5 enemies. Grandstander's Ballad for 10s: DPS = +5% damage, Tank = -5% damage taken, Healer = +5% Outgoing Healing.", debuff: "Role-based 5% buff", cooldown: 60, set: "None", source: "Vault of the Nine (Bard)", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Combat Advantage","value":450},{"stat":"Forte","value":450}] },
    { name: "Sovereign's Sporestaff", type: "debuff", power: "Poison damage to nearby foes. Enemies -30% Movement Speed, you +10% Movement Speed for 10s. Doubled in Underdark.", debuff: "30% slow (10s)", cooldown: 60, set: "None", source: "Demonweb Pits Campaign (Mod 26)", itemLevel: 1200, combinedRating: 1020, stats: [{"stat":"Power","value":900},{"stat":"Combat Advantage","value":900},{"stat":"Awareness","value":900}] },
    { name: "Trobriand's Overcharged Ring", type: "damage", power: "Stronger Trobriand's Ring: electric stun + damage. Spawns Scaladar for 15s.", debuff: "None (set bonus value)", cooldown: 60, set: "Armaments of Construct Demise", source: "Mythic refinement upgrade of Trobriand's Ring (Lair of the Mad Mage)", itemLevel: 1800, combinedRating: 1440, stats: [{"stat":"Power","value":2700},{"stat":"Defense","value":1350},{"stat":"Critical Avoidance","value":1350}] },
    { name: "Tymora's Spinning Coin", type: "utility", power: "Coin knocks enemies down + RNG: blessing (allies +9% DR + HoT) OR curse (enemies +15% damage taken). 15s.", debuff: "RNG ally HoT or 15% group debuff", cooldown: 60, set: "None", source: "Tymora's Gift event (Gift of Tymora drop)", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Strike","value":450},{"stat":"Combat Advantage","value":450}] },
    { name: "Vibrating Erratic Drift Globe", type: "tank", power: "Stronger Erratic Drift Globe: Aura grants allies +6% Deflect, enemies -3% Crit Strike and -3% Deflect. 50' range, 10s.", debuff: "Ally Deflect + enemy stat shred", cooldown: 60, set: "Reflective Armaments", source: "Mythic refinement upgrade of Erratic Drift Globe (Undermountain)", itemLevel: 1800, combinedRating: 1440, stats: [{"stat":"Max HP","value":5400},{"stat":"Defense","value":2700},{"stat":"Deflect","value":1350}] },
    { name: "Wand of Domination", type: "debuff", power: "Frontal gaze deals damage + charms 4s. Targets take +7.5% damage for 10s.", debuff: "7.5% more damage taken (10s)", cooldown: 60, set: "Ruthless Domination", source: "Halls of Sorcere trial (Mod 25 Menzoberranzan)", itemLevel: 1500, combinedRating: 1275, stats: [{"stat":"Power","value":1125},{"stat":"Critical Severity","value":1125},{"stat":"Accuracy","value":1125}] },
    { name: "Waukeen's Horde", type: "damage", power: "Summons Horde from sky for impact damage + RNG: treasure (daze + DoT) or rust cloud (slow + DoT).", debuff: "None (RNG)", cooldown: 60, set: "None", source: "? (needs verification — Waukeen-themed)", itemLevel: 600, combinedRating: 510, stats: [{"stat":"Power","value":450},{"stat":"Critical Severity","value":450},{"stat":"Critical Strike","value":450}] },
    { name: "Wrath of Kossuth", type: "debuff", power: "Self cloak of flames 10s: +7.5% Awareness/Crit Avoidance. Attackers burn + Primordial Burn (+7.5% damage taken for 10s).", debuff: "7.5% more damage taken (on hit)", cooldown: 60, set: "None", source: "Mountain of Flame (Mod 29)", itemLevel: 2000, combinedRating: 1700, stats: [{"stat":"Critical Avoidance","value":1500},{"stat":"Deflect","value":1500},{"stat":"Deflect Severity","value":1500}] },
  ];

  // ============================================================
  // DUNGEON / TRIAL RANKING (unified)
  // Ranked by debuff strength: + damage taken or − damage resistance.
  // Higher rank = stronger group damage amplification.
  // ============================================================
  var groupRanking = [
    { rank: 1,  name: "Demogorgon's Reach",            effect: "+3% damage taken per stack, up to +18% (6 stacks)",                       duration: "6s per stack" },
    { rank: 2,  name: "Charm of the Serpent",          effect: "+16% damage taken by enemies (cone)",                                     duration: "10s" },
    { rank: 3,  name: "Halaster's Blast Scepter",      effect: "−15% enemy damage resistance",                                            duration: "10s" },
    { rank: 4,  name: "Mythallar Fragment",            effect: "−15% enemy damage resistance",                                            duration: "10s" },
    { rank: 5,  name: "Nightflame Censer",             effect: "+12.5% damage taken, −11.9% enemy damage dealt + DoT",                    duration: "10s" },
    { rank: 6,  name: "Wyvern-Venom Coated Knives",    effect: "+12% damage taken, −12% enemy damage dealt",                              duration: "10s" },
    { rank: 7,  name: "Dragonbone Blades",             effect: "+12% damage taken, −12% enemy damage dealt",                              duration: "10s" },
    { rank: 8,  name: "Portable Spelljammer Detector", effect: "+12% damage taken (single-target arcane disrupt)",                        duration: "10s" },
    { rank: 9,  name: "Beacon of Meteor Swarm",        effect: "+10% damage taken + stun + DoT (AoE meteor storm)",                       duration: "10s" },
    { rank: 10, name: "Heart of the Volcano",          effect: "+10% damage taken from all sources + 10% self DR (line)",                 duration: "10s" },
    { rank: 11, name: "Jewel of the Caldera",          effect: "+10% damage taken (lunge, line)",                                         duration: "10s" },
    { rank: 12, name: "Marco's Mystic Marker",         effect: "+10% damage taken from all sources (single-target rapid arcane)",         duration: "10s" },
    { rank: 13, name: "Crystal of Soul's Flight",      effect: "+10% damage taken (all sources) + 15% from your attacks",                 duration: "10s" },
    { rank: 14, name: "Lantern of Revelation",         effect: "+10% damage taken by enemies (AoE)",                                      duration: "10s" },
    { rank: 15, name: "Thirst",                        effect: "+10% damage taken by enemies (lunge, line)",                              duration: "10s" },
    { rank: 16, name: "Frozen Storyteller's Journal",  effect: "+10% ally damage + 10% incoming damage reduction + stun",                 duration: "15s" },
    { rank: 17, name: "Black Dragon's Mark",           effect: "−10% enemy damage resistance (acid ball)",                                duration: "10s" },
    { rank: 18, name: "Heart of the Black Dragon",     effect: "+10% damage taken by enemies (line, shorter duration)",                   duration: "6s" },
    { rank: 19, name: "Broken Halo",                   effect: "+9% damage taken + stuns lesser enemies (AoE light burst)",               duration: "10s" },
    { rank: 20, name: "Marilith Mask",                 effect: "+7.5% damage taken (laser beams)",                                        duration: "10s" },
    { rank: 21, name: "Realm Engine Core",             effect: "+7.5% damage taken + self shield 15% HP (single-target)",                 duration: "10s" },
    { rank: 22, name: "Sealing Parchment",             effect: "+7.5% damage taken + DoT + self Deflect/Sev",                             duration: "10s" },
    { rank: 23, name: "Wand of Domination",            effect: "+7.5% damage taken + 4s charm (frontal gaze)",                            duration: "10s" },
    { rank: 24, name: "Wrath of Kossuth",              effect: "+7.5% damage taken (Primordial Burn) on attackers",                       duration: "10s" },
    { rank: 25, name: "Bloodbrass Pistol",             effect: "+6% damage taken (single-target Blunderbuss)",                            duration: "10s" },
    { rank: 26, name: "Demon Skull",                   effect: "+5% damage taken + −5% Accuracy (3-imp swarm)",                           duration: "10s" },
    { rank: 27, name: "Tentacle Rod",                  effect: "+5% damage taken + −5% Movement/Awareness + daze",                        duration: "10s" },
    { rank: 28, name: "Vanguard's Banner",             effect: "+5% damage taken + 5,000 ally Power/Crit Avoidance",                      duration: "30s" },
    { rank: 29, name: "Sparkling Fey Emblem",          effect: "+5% damage taken + 5% ally Defense/Crit Avoidance",                       duration: "15s" },
    { rank: 30, name: "Neverwinter's Standard",        effect: "+5% damage taken + 5% ally Recharge Speed",                               duration: "15s" },
    { rank: 31, name: "Alaric's Artillery Beacon",     effect: "Up to +5% damage taken + stun (AoE)",                                     duration: "10s" },
  ];

  // ============================================================
  // ARTIFACT SETS
  // ============================================================
  var artifactSets = [
    { name: "Apprentices' Spoils", pieces: "Arcturia's Music Box + Jhesiyra's Tattered Mantle + Trobriand's Conduction Cable", bonus: "When you use a Daily Power, deal 15% more damage vs monsters not facing you for 10s.", best: "DPS (Best in Slot)" },
    { name: "Armaments of the Wyvern", pieces: "Wyvern-Venom Coated Knives + Wyvern's Eye Necklace + Wyvern-Skin Belt", bonus: "Daily Power creates Rune of Aggression: allies gain +5% Power, +5% Crit Severity, +5% damage for 6s.", best: "Support DPS" },
    { name: "Reflective Armaments", pieces: "Erratic Drift Globe + Reflective Collar + Mirror-Plated Belt", bonus: "Daily Power creates Rune of Fortification: allies gain +5% Defense, +5% Deflect, -5% damage taken for 6s.", best: "Support Tank" },
    { name: "Enchanted Thumb", pieces: "Staff of Flowers + Woven Vine + Blooming Cord", bonus: "Daily Power creates Rune of Cooperation: allies gain +5% Awareness, +5% CA, CC immunity for 6s.", best: "Support" },
    { name: "Valhalla's Rebuke", pieces: "Horn of Valhalla + Cloak of Valhalla + Belt of Valhalla", bonus: "When foe hits you, they deal 1% less damage for 6s, stacks 5x (5% max).", best: "Tank (Best in Slot)" },
    { name: "Tiamat", pieces: "Tiamat's Orb of Majesty + Amulet of Tiamat's Demise + Tiamat Sash", bonus: "+5% Outgoing Healing and +5% Incoming Healing.", best: "Healer (Best in Slot)" },
    { name: "Dark Remnant", pieces: "Book of Vile Darkness + Engine Master's Mantle + Whip of the Erinyes", bonus: "+5% damage vs demons/devils/fiends, +2.5% vs others.", best: "DPS (Avernus/IC)" },
    { name: "Lostmauth's Hoard", pieces: "Lostmauth's Horn + Lostmauth's Hoard Necklace + Golden Belt of Puissance", bonus: "On crit, additional hit equal to your Damage stat.", best: "DPS (crit builds)" },
    { name: "Apocalypse", pieces: "Apocalypse Dagger + Apocalypse Choker + Apocalypse Bindings", bonus: "On crit, target takes +1% more damage for 5s, stacks 5x (5% group debuff).", best: "Support" },
    { name: "Star Set", pieces: "Sparkling Fey Emblem + Starshard Choker + Twinkle of the Stars", bonus: "Up to 10% additional damage or healing based on HP% difference.", best: "DPS / Healer" },
    { name: "Demon Lords' Immortality", pieces: "Shard of Orcus' Wand + Baphomet's Infernal Talisman + Demogorgon's Girdle", bonus: "Up to 10% additional damage based on HP% difference.", best: "DPS (budget)" },
    { name: "Mad Dash", pieces: "Halaster's Blast Scepter + Necklace/Belt of the Mad Mage", bonus: "Stand still 3s: +5% damage and movement speed.", best: "DPS (situational)" },
    { name: "Set of the Serpent", pieces: "Charm of the Serpent + Skin of the Serpent + Wrap of the Serpent", bonus: "Moving 3s: +1% damage, up to 5% after 15s. Resets standing still 5s.", best: "DPS (hard to use)" },
    { name: "Diamond Set", pieces: "Refulgent Diamond Pin + Iridescent Diamond Pendant + Scintilliant Diamond Buckle", bonus: "Stand still 3s: -5% damage taken, +5% Awareness.", best: "Tank (situational)" },
    { name: "Armaments of Construct Demise", pieces: "Trobriand's Ring + Electric Collar + Chained Restraints", bonus: "Daily Power: +5% damage, -5% damage taken for 10s.", best: "Hybrid" },
    { name: "Vistani", pieces: "Tarokka Deck + Vistani Pendant + Vistani Raiments", bonus: "Single-target AoE: target takes +5% damage for 5s.", best: "Tank support" },
    { name: "Soulmonger", pieces: "Decanter of Atropal Essence + Mantle/Cincture of Atropal Essence", bonus: "On heal: Temp HP = 25% of heal, up to 5% max HP (30s CD).", best: "Tank sustain" },
    { name: "Storyteller's Journals", pieces: "2-3 of 4 Journals", bonus: "2pc: +1 all ability scores, +0.5% Power, +5k HP per journal. 3pc: Crit = bonus damage hit.", best: "DPS (expensive)" },
    { name: "Hearts of the Dragons", pieces: "Any 3 of 5 Dragon Hearts", bonus: "+10% Recharge Speed.", best: "Cooldown builds" },
    { name: "Lathander", pieces: "Eye of Lathander + Lathander's Cloak + Greater Lathander's Belt", bonus: "On revive: allies heal 50% HP, +1% Awareness, injury immunity.", best: "Niche" },
    { name: "Redeemed", pieces: "Memories + Divine Focus + Celestial Sash", bonus: "+3% Incoming Healing. When healed: +5% Power for 6s.", best: "Healer (rare)" },
  ];

  // ============================================================
  // RENDERING
  // ============================================================
  var searchInput = document.getElementById("search");
  var filterType = document.getElementById("filter-type");
  var allControls = document.getElementById("all-controls");

  var typeLabels = { debuff: "Group Debuff", personal: "Personal DPS", tank: "Tank / Mitigation", utility: "Utility / Healing", damage: "Damage Only" };
  var typeBadgeClass = { debuff: "stat-negative", personal: "stat-positive", tank: "stat-neutral", utility: "stat-neutral", damage: "stat-positive" };

  var STAT_LABELS = {
    Power: "Power",
    "Critical Strike": "Critical Strike",
    "Critical Severity": "Critical Severity",
    "Critical Avoidance": "Critical Avoidance",
    "Combat Advantage": "Combat Advantage",
    Defense: "Defense",
    Deflect: "Deflect",
    "Deflect Severity": "Deflect Severity",
    Accuracy: "Accuracy",
    Awareness: "Awareness",
    Forte: "Forte",
    "Incoming Healing": "Incoming Healing",
    "Outgoing Healing": "Outgoing Healing",
    "Control Resist": "Control Resist",
    "Control Bonus": "Control Bonus",
    "Gold Bonus": "Gold Bonus",
    "Max HP": "Max HP",
    "Stamina Regen": "Stamina Regen"
  };
  function prettyArtifactStat(key) { return STAT_LABELS[key] || key; }

  function renderAllArtifacts() {
    var query = searchInput.value.trim().toLowerCase();
    var typeVal = filterType.value;

    var filtered = artifacts.filter(function (a) {
      if (query && (a.name + " " + a.power + " " + a.set).toLowerCase().indexOf(query) === -1) return false;
      if (typeVal && a.type !== typeVal) return false;
      return true;
    });

    var html = "";
    for (var i = 0; i < filtered.length; i++) {
      var a = filtered[i];
      html += '<div class="art-card" data-idx="' + i + '">';
      html += '<div class="art-card-header">';
      html += '<span class="art-card-name">';
      if (a.image) {
        html += '<img loading="lazy" class="art-list-icon" src="' + escapeHtml(a.image) + '" alt="">';
      }
      html += escapeHtml(a.name) + '</span>';
      html += '<span><span class="' + (typeBadgeClass[a.type] || '') + '" style="font-size:0.78rem;">' + (typeLabels[a.type] || a.type) + '</span> <span class="toggle-arrow">&#9654;</span></span>';
      html += '</div>';
      html += '<div class="art-card-body">';
      if (a.image) {
        html += '<img loading="lazy" class="art-icon" src="' + escapeHtml(a.image) + '" alt="' + escapeHtml(a.name) + '">';
      }
      html += '<div class="art-effect">' + escapeHtml(a.power) + '</div>';
      if (a.itemLevel || a.combinedRating) {
        html += '<div class="art-il-row">';
        if (a.itemLevel)       html += '<span class="art-il-pill"><span class="art-il-label">Item Level</span><span class="art-il-value">' + a.itemLevel.toLocaleString() + '</span></span>';
        if (a.combinedRating)  html += '<span class="art-il-pill"><span class="art-il-label">Combined Rating</span><span class="art-il-value">' + a.combinedRating.toLocaleString() + '</span></span>';
        html += '</div>';
      }
      if (a.stats && a.stats.length > 0) {
        html += '<div class="art-stats-block">';
        html += '<div class="art-stats-title">Stats at Mythic</div>';
        html += '<div class="art-stats-grid">';
        for (var si = 0; si < a.stats.length; si++) {
          var st = a.stats[si];
          var isPct = st.stat === 'StaminaRegen';
          html += '<div class="art-stat-row">';
          html += '<span class="art-stat-name">' + escapeHtml(prettyArtifactStat(st.stat)) + '</span>';
          html += '<span class="art-stat-value">' + (isPct ? st.value + '%' : '+' + st.value.toLocaleString()) + '</span>';
          html += '</div>';
        }
        html += '</div></div>';
      }
      if (a.debuff && a.debuff !== "None") {
        html += '<div class="art-info-row"><span class="art-info-label">Buff/Debuff</span><span class="art-info-value">' + escapeHtml(a.debuff) + '</span></div>';
      }
      html += '<div class="art-info-row"><span class="art-info-label">Cooldown</span><span class="art-info-value">' + a.cooldown + 's</span></div>';
      if (a.set && a.set !== "None") {
        html += '<div class="art-info-row"><span class="art-info-label">Set</span><span class="art-info-value">' + escapeHtml(a.set) + '</span></div>';
      }
      html += '<div class="art-info-row"><span class="art-info-label">Source</span><span class="art-info-value">' + escapeHtml(a.source) + '</span></div>';
      html += '</div></div>';
    }
    document.getElementById("all-list").innerHTML = html || '<div class="empty-state">No artifacts match your filters</div>';
  }

  function findArtifactImage(name) {
    for (var i = 0; i < artifacts.length; i++) {
      if (artifacts[i].name === name && artifacts[i].image) return artifacts[i].image;
    }
    return "";
  }

  function renderRanking(data, containerId) {
    var html = "";
    for (var i = 0; i < data.length; i++) {
      var r = data[i];
      var img = findArtifactImage(r.name);
      html += '<div class="rank-card">';
      if (img) {
        html += '<img loading="lazy" class="art-icon" src="' + escapeHtml(img) + '" alt="' + escapeHtml(r.name) + '">';
      }
      html += '<div style="font-weight:600;"><span style="color:var(--highlight);margin-right:0.5rem;">#' + r.rank + '</span>' + escapeHtml(r.name) + '</div>';
      html += '<div class="art-effect" style="margin-top:0.4rem;">' + escapeHtml(r.effect) + '</div>';
      html += '<div style="font-size:0.78rem;color:var(--text-muted);margin-top:0.25rem;">Duration: ' + r.duration + '</div>';
      html += '</div>';
    }
    document.getElementById(containerId).innerHTML = html;
  }

  function renderSets() {
    var html = "";
    for (var i = 0; i < artifactSets.length; i++) {
      var s = artifactSets[i];
      html += '<div class="art-card" data-idx="' + i + '">';
      html += '<div class="art-card-header">';
      html += '<span class="art-card-name">' + escapeHtml(s.name) + '</span>';
      html += '<span style="font-size:0.78rem;color:var(--text-muted);">' + escapeHtml(s.best) + ' <span class="toggle-arrow">&#9654;</span></span>';
      html += '</div>';
      html += '<div class="art-card-body">';
      html += '<div style="font-size:0.85rem;color:var(--text-muted);margin-bottom:0.4rem;">' + escapeHtml(s.pieces) + '</div>';
      html += '<div class="art-set">' + escapeHtml(s.bonus) + '</div>';
      html += '</div></div>';
    }
    document.getElementById("sets-list").innerHTML = html;
  }

  // ============================================================
  // TAB SWITCHING
  // ============================================================
  var tabs = document.querySelectorAll(".view-tab");
  tabs.forEach(function (tab) {
    tab.addEventListener("click", function () {
      tabs.forEach(function (t) { t.classList.remove("active"); });
      tab.classList.add("active");
      document.querySelectorAll(".art-view").forEach(function (v) { v.classList.remove("active"); });
      document.getElementById("view-" + tab.getAttribute("data-tab")).classList.add("active");
      allControls.style.display = tab.getAttribute("data-tab") === "all" ? "" : "none";

      if (tab.getAttribute("data-tab") === "ranking") renderRanking(groupRanking, "ranking-list");
      if (tab.getAttribute("data-tab") === "sets") renderSets();
    });
  });

  // ============================================================
  // EVENT HANDLERS
  // ============================================================
  document.querySelectorAll(".art-container").forEach(function (container) {
    container.addEventListener("click", function (e) {
      var card = e.target.closest(".art-card");
      if (card) card.classList.toggle("open");
    });
  });

  searchInput.addEventListener("input", renderAllArtifacts);
  filterType.addEventListener("change", renderAllArtifacts);

  // Initial render
  renderAllArtifacts();
})();
