"""
build-data.py — Convert NWCB JSON data files to JS global-variable files.

Run from the website/ folder:
    python build-data.py

Reads JSON from ../data/ and writes JS files to ./data/
Each JS file assigns the JSON content to a global const variable,
so the browser can load it via <script> tags (works on file:// and https://).
"""

import json
import os
from datetime import datetime

# Where this script lives (website/)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SOURCE_DIR = os.path.join(SCRIPT_DIR, "..", "data")
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "data")

# Mapping: source JSON filename -> (output JS filename, JS variable name)
FILE_MAP = {
    "mounts.json":                  ("mounts.js",                  "MOUNTS_DATA"),
    "mount_combat_powers.json":     ("mount-combat-powers.js",     "MOUNT_COMBAT_POWERS_DATA"),
    "mount_equip_powers.json":      ("mount-equip-powers.js",      "MOUNT_EQUIP_POWERS_DATA"),
    "mount_insignia_bonuses.json":  ("mount-insignia-bonuses.js",  "MOUNT_INSIGNIA_BONUSES_DATA"),
    "mount_insignias.json":         ("mount-insignias.js",         None),  # Special: object with tierScaling + insignias
    "companions.json":              ("companions.js",              "COMPANIONS_DATA"),
    "companion_powers.json":        ("companion-powers.js",        "COMPANION_POWERS_DATA"),
    "companion_enhancements.json":  ("companion-enhancements.js",  "COMPANION_ENHANCEMENTS_DATA"),
}

def build_header(source_name):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return (
        f"// Auto-generated by build-data.py on {ts}\n"
        f"// Source: ../data/{source_name}\n"
        f"// Do not edit — re-run build-data.py to regenerate.\n\n"
    )

def convert_file(source_name, output_name, var_name):
    source_path = os.path.join(SOURCE_DIR, source_name)
    output_path = os.path.join(OUTPUT_DIR, output_name)

    if not os.path.exists(source_path):
        print(f"  SKIP  {source_name} (not found)")
        return False

    with open(source_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    header = build_header(source_name)

    # Special handling for mount_insignias.json (object, not array)
    if var_name is None and source_name == "mount_insignias.json":
        tier_scaling = data.get("tierScaling", {})
        insignias = data.get("insignias", [])
        js_content = header
        js_content += f"const MOUNT_INSIGNIAS_TIER_SCALING = {json.dumps(tier_scaling, indent=2)};\n\n"
        js_content += f"const MOUNT_INSIGNIAS_DATA = {json.dumps(insignias, indent=2)};\n"
    else:
        js_content = header + f"const {var_name} = {json.dumps(data, indent=2)};\n"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"  OK    {source_name} -> data/{output_name}")
    return True

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print(f"Building JS data files...")
    print(f"  Source: {os.path.abspath(SOURCE_DIR)}")
    print(f"  Output: {os.path.abspath(OUTPUT_DIR)}")
    print()

    success = 0
    for source_name, (output_name, var_name) in FILE_MAP.items():
        if convert_file(source_name, output_name, var_name):
            success += 1

    print(f"\nDone: {success}/{len(FILE_MAP)} files converted.")

if __name__ == "__main__":
    main()
