"""
build-data.py — Convert NWCB JSON data files to JS global-variable files.

Run from the website/ folder:
    python build-data.py

Reads JSON from ../data/ and writes JS files to ./data/
Each JS file assigns the JSON content to a global const variable,
so the browser can load it via <script> tags (works on file:// and https://).
"""

import json
import os
from datetime import datetime

# Where this script lives (website/)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SOURCE_DIR = os.path.join(SCRIPT_DIR, "..", "data")
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "data")

# Mapping: source JSON filename -> (output JS filename, JS variable name)
FILE_MAP = {
    "mounts.json":                  ("mounts.js",                  "MOUNTS_DATA"),
    "mount_combat_powers.json":     ("mount-combat-powers.js",     "MOUNT_COMBAT_POWERS_DATA"),
    "mount_equip_powers.json":      ("mount-equip-powers.js",      "MOUNT_EQUIP_POWERS_DATA"),
    "mount_insignia_bonuses.json":  ("mount-insignia-bonuses.js",  "MOUNT_INSIGNIA_BONUSES_DATA"),
    "mount_insignias.json":         ("mount-insignias.js",         None),  # Special: object with tierScaling + insignias
    "mount_collars.json":           ("mount-collars.js",           "MOUNT_COLLARS_DATA"),
    "companions.json":              ("companions.js",              "COMPANIONS_DATA"),
    "companion_powers.json":        ("companion-powers.js",        "COMPANION_POWERS_DATA"),
    "companion_enhancements.json":  ("companion-enhancements.js",  "COMPANION_ENHANCEMENTS_DATA"),
    "buffs.json":                   ("buffs.js",                   "BUFFS_DATA"),
    "artifacts.json":               ("artifacts.js",               "ARTIFACTS_DATA"),
    "classes.json":                 ("classes.js",                 "CLASSES_DATA"),
    "races.json":                   ("races.js",                   "RACES_DATA"),
    "campaign_boons.json":          ("campaign-boons.js",          "CAMPAIGN_BOONS_DATA"),
    "guild_boons.json":             ("guild-boons.js",             "GUILD_BOONS_DATA"),
    "companion_gear.json":          ("companion-gear.js",          "COMPANION_GEAR_DATA"),
    "gear.json":                    ("gear.js",                    "GEAR_DATA"),
    "enchants.json":                ("enchants.js",                "ENCHANTS_DATA"),
    "overloads.json":               ("overloads.js",               "OVERLOADS_DATA"),
    "kits.json":                    ("kits.js",                    "KITS_DATA"),
    "general_feats.json":           ("general-feats.js",           "GENERAL_FEATS_DATA"),
}

def build_header(source_name):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return (
        f"// Auto-generated by build-data.py on {ts}\n"
        f"// Source: ../data/{source_name}\n"
        f"// Do not edit — re-run build-data.py to regenerate.\n\n"
    )

# ---- POWER-TAGS-2 effect vocabulary validator (docs/plans/effect_vocabulary.md, step 2.1) ----
# Any `fx` record outside the vocabulary FAILS the classes.json build loudly, so drift cannot
# creep back in. Entries without `fx` are not checked (the old free-form blocks are records only).
FX_COMMON = {"kind", "when", "gate", "requiresFeat", "requiresFeature", "requiresSlotted", "provisional", "missing", "note", "paragon", "slot"}
FX_KINDS = {
    "hit":      {"magnitude", "count", "targets", "areaShare", "radius", "damageType", "element", "delaySeconds", "name", "scalesWith"},
    "dot":      {"magnitude", "perTick", "ticks", "seconds", "stacking", "maxStacks", "damageType", "element", "name", "targets", "scalesWith"},
    "buff":     {"stats", "scope", "seconds", "appliesTo", "stacks", "maxStacks", "radius", "name"},
    "debuff":   {"stats", "personal", "appliesTo", "seconds", "maxStacks", "name", "targets"},
    "stack":    {"resource", "op", "amount", "target", "max", "min", "seconds", "targets", "scalesWith"},
    "resource": {"pool", "op", "amount", "pctOfBar"},
    "cooldown": {"targets", "op", "seconds", "pct"},
    "proc":     {"effects", "name"},
    "control":  {"control", "seconds", "perStack", "targets"},
    "heal":     {"magnitude", "pctMaxHp", "pctOfDamage", "scope", "seconds", "perTick", "name"},
    "shield":   {"magnitude", "pctMaxHp", "pctOfHealed", "scope", "seconds", "name"},
    "mod":      {"target", "field", "op", "value", "addFx"},
}
FX_EVENTS = {"cast", "hit", "crit", "dotTick", "kill", "combatStart", "periodic", "stackSpent", "stackReached",
             "stackApplied", "stackRemoved", "takeHit", "block", "deflect", "dodge", "buffApplied", "buffRefreshed"}
FX_WHEN = {"on", "from", "chance", "icdSeconds", "every", "resource", "amount", "name"}
FX_POOLS = {"actionPoints", "stamina", "divinity", "rage", "performance", "soulweave", "vengeance", "stealthMeter"}
FX_STACKS = {"Chill", "Arcane Mastery", "Smolder", "Soul Spark", "Soul Investiture", "Curse", "Spell Twisting",
             "Stealth", "Sly Flourish", "Vengeance"}

def _fx_extra_stacks():
    p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "docs", "plans", "effect_vocabulary_resources.json")
    try:
        with open(p, "r", encoding="utf-8") as f:
            return set(json.load(f).get("stacks", []))
    except (OSError, ValueError):
        return set()

def _fx_check_record(rec, where, errs, stacks):
    if not isinstance(rec, dict):
        errs.append(f"{where}: record is not an object"); return
    kind = rec.get("kind")
    if kind not in FX_KINDS:
        errs.append(f"{where}: unknown kind {kind!r}"); return
    bad = set(rec) - FX_COMMON - FX_KINDS[kind]
    if bad:
        errs.append(f"{where}: {kind} has fields outside the vocabulary: {sorted(bad)}")
    w = rec.get("when")
    if w is not None:
        if not isinstance(w, dict) or w.get("on") not in FX_EVENTS:
            errs.append(f"{where}: bad trigger {w!r}")
        elif set(w) - FX_WHEN:
            errs.append(f"{where}: trigger fields outside the vocabulary: {sorted(set(w) - FX_WHEN)}")
    if kind == "stack" and rec.get("resource") not in stacks:
        errs.append(f"{where}: unknown stack resource {rec.get('resource')!r}")
    if kind == "resource" and rec.get("pool") not in FX_POOLS:
        errs.append(f"{where}: unknown pool {rec.get('pool')!r}")
    for k in ("magnitude", "count", "amount", "seconds", "perTick", "ticks", "pct", "pctMaxHp", "pctOfBar"):
        v = rec.get(k)
        if v is not None and not isinstance(v, (int, float)):
            errs.append(f"{where}: {k} must be a number, got {v!r}")
    if kind == "proc":
        for i, sub in enumerate(rec.get("effects") or []):
            _fx_check_record(sub, f"{where}.effects[{i}]", errs, stacks)
    if kind == "mod":
        for i, sub in enumerate(rec.get("addFx") or []):
            _fx_check_record(sub, f"{where}.addFx[{i}]", errs, stacks)

def validate_fx(data):
    """Return a list of error strings for every `fx` record in classes.json data."""
    errs, stacks = [], FX_STACKS | _fx_extra_stacks()
    def walk(o, path):
        if isinstance(o, dict):
            if "fx" in o:
                if not isinstance(o["fx"], list):
                    errs.append(f"{path}/{o.get('name', '?')}: fx must be a list")
                else:
                    for i, rec in enumerate(o["fx"]):
                        _fx_check_record(rec, f"{path}/{o.get('name', '?')}.fx[{i}]", errs, stacks)
            for k, v in o.items():
                if k != "fx": walk(v, path + "/" + str(o.get("name", k)) if isinstance(v, (dict, list)) else path)
        elif isinstance(o, list):
            for x in o: walk(x, path)
    walk(data, "")
    return errs

def convert_file(source_name, output_name, var_name):
    source_path = os.path.join(SOURCE_DIR, source_name)
    output_path = os.path.join(OUTPUT_DIR, output_name)

    if not os.path.exists(source_path):
        print(f"  SKIP  {source_name} (not found)")
        return False

    # A syntax error in one source file must not abort the whole build —
    # that used to leave a half-fresh, half-stale data/ directory.
    try:
        with open(source_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"  FAIL  {source_name}: invalid JSON ({e}) — output left unchanged")
        return False

    # POWER-TAGS-2: the effect vocabulary is enforced on classes.json (step 2.1).
    if source_name == "classes.json":
        fx_errs = validate_fx(data)
        if fx_errs:
            print(f"  FAIL  {source_name}: {len(fx_errs)} effect record(s) outside the vocabulary - output left unchanged")
            for e in fx_errs[:25]: print(f"          {e}")
            return False

    header = build_header(source_name)

    # Special handling for mount_insignias.json (object, not array)
    if var_name is None and source_name == "mount_insignias.json":
        tier_scaling = data.get("tierScaling", {})
        insignias = data.get("insignias", [])
        js_content = header
        js_content += f"const MOUNT_INSIGNIAS_TIER_SCALING = {json.dumps(tier_scaling, indent=2)};\n\n"
        js_content += f"const MOUNT_INSIGNIAS_DATA = {json.dumps(insignias, indent=2)};\n"
    else:
        js_content = header + f"const {var_name} = {json.dumps(data, indent=2)};\n"

    # A failed WRITE (disk full, file locked, permissions) must not abort the
    # whole build either — and must be loud, or the output file could sit
    # there truncated while the build claims success.
    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(js_content)
    except OSError as e:
        print(f"  FAIL  {source_name}: write error ({e}) — data/{output_name} may be incomplete, re-run after fixing")
        return False

    print(f"  OK    {source_name} -> data/{output_name}")
    return True

def build_preview_data():
    """Scan images/preview/ and emit data/preview.js with discovered files.

    Layout:
        images/preview/gear/<Class>/*.{png,jpg,webp,...}
        images/preview/companions/*.{...}
        images/preview/mounts/*.{...}
        images/preview/other/*.{...}
    """
    preview_root = os.path.join(SCRIPT_DIR, "images", "preview")
    if not os.path.isdir(preview_root):
        print("  SKIP  preview (images/preview/ missing)")
        return False

    image_exts = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
    # "All Classes" holds gear with no class requirement (e.g. Mod 33.5 Renewed gear)
    classes = ["All Classes", "Barbarian", "Bard", "Cleric", "Fighter", "Paladin",
               "Ranger", "Rogue", "Warlock", "Wizard"]

    def list_images(rel_dir):
        abs_dir = os.path.join(preview_root, rel_dir)
        if not os.path.isdir(abs_dir):
            return []
        items = []
        for name in sorted(os.listdir(abs_dir)):
            if name.startswith("."):
                continue
            ext = os.path.splitext(name)[1].lower()
            if ext not in image_exts:
                continue
            # file path is relative to images/preview/ — preview.html prefixes "images/preview/"
            items.append({"file": rel_dir.replace(os.sep, "/") + "/" + name})
        return items

    def list_gear_for_class(cls):
        """Walk gear/<class>/. If it contains slot subfolders, walk one more level
        and tag each entry with its slot. If files are flat at the class level
        (no subfolders), return them without a slot tag (back-compat)."""
        class_dir = os.path.join(preview_root, "gear", cls)
        if not os.path.isdir(class_dir):
            return []
        # Detect slot subfolders (any subdirectory inside the class folder)
        subdirs = [
            d for d in sorted(os.listdir(class_dir))
            if not d.startswith(".") and os.path.isdir(os.path.join(class_dir, d))
        ]
        if subdirs:
            items = []
            for slot in subdirs:
                slot_items = list_images(os.path.join("gear", cls, slot))
                for it in slot_items:
                    it["slot"] = slot
                    items.append(it)
            # Also include any files dropped at the class root (untagged)
            root_items = list_images(os.path.join("gear", cls))
            return items + root_items
        # No subfolders → flat layout, no slot tags
        return list_images(os.path.join("gear", cls))

    gear = {cls: list_gear_for_class(cls) for cls in classes}
    companions = list_images("companions")
    mounts = list_images("mounts")
    other = list_images("other")

    payload = {"gear": gear, "companions": companions, "mounts": mounts, "other": other}

    output_path = os.path.join(OUTPUT_DIR, "preview.js")
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    js = (
        f"// Auto-generated by build-data.py on {ts}\n"
        f"// Source: images/preview/ (gear/<class>/, companions/, mounts/, other/)\n"
        f"// Drop image files into the matching folder, then re-run build-data.py.\n\n"
        f"window.PREVIEW_DATA = {json.dumps(payload, indent=2)};\n"
    )
    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(js)
    except OSError as e:
        print(f"  FAIL  images/preview/: write error ({e}) — data/preview.js may be incomplete, re-run after fixing")
        return False

    total = sum(len(v) for v in gear.values()) + len(companions) + len(mounts) + len(other)
    print(f"  OK    images/preview/ -> data/preview.js ({total} images)")
    return True


def build_name_aliases():
    """Generate data/name-aliases.js from the formerNames fields on companions
    and mounts, so a rename never silently blanks a slot in a saved build.

    Saved and shared builds store companions and mounts by NAME. When an entry
    is renamed to match the in-game name, every stored build still holds the
    old one. Toon Forge rewrites them on load using these maps.

    formerNames on the source JSON is the single source of truth - add the old
    name there when renaming and this file regenerates itself.
    """
    out = {}
    for src, key in (("companions.json", "COMPANION_NAME_ALIASES"),
                     ("mounts.json", "MOUNT_NAME_ALIASES")):
        path = os.path.join(SOURCE_DIR, src)
        if not os.path.exists(path):
            out[key] = {}
            continue
        with open(path, "r", encoding="utf-8") as f:
            rows = json.load(f)
        amap = {}
        for row in rows:
            for old in (row.get("formerNames") or []):
                if old and old != row.get("name"):
                    amap[old] = row["name"]
        out[key] = dict(sorted(amap.items()))
    dest = os.path.join(OUTPUT_DIR, "name-aliases.js")
    lines = [
        "// Auto-generated by build-data.py on " + datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "// Source: formerNames on ../data/companions.json and ../data/mounts.json",
        "// Do not edit - add the old name to formerNames and re-run build-data.py.",
        "//",
        "// Saved builds store companions and mounts by NAME, so a rename would",
        "// silently blank the slot. Toon Forge rewrites old names on load.",
        "",
    ]
    for key, amap in out.items():
        lines.append("const " + key + " = " + json.dumps(amap, indent=2, ensure_ascii=False) + ";")
        lines.append("")
    with open(dest, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    n = sum(len(v) for v in out.values())
    print("  OK    formerNames -> data/name-aliases.js (%d aliases)" % n)
    return True


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print(f"Building JS data files...")
    print(f"  Source: {os.path.abspath(SOURCE_DIR)}")
    print(f"  Output: {os.path.abspath(OUTPUT_DIR)}")
    print()

    success = 0
    for source_name, (output_name, var_name) in FILE_MAP.items():
        if convert_file(source_name, output_name, var_name):
            success += 1

    if build_preview_data():
        success += 1

    if build_name_aliases():
        success += 1

    total = len(FILE_MAP) + 2
    print(f"\nDone: {success}/{total} files converted.")

if __name__ == "__main__":
    main()
