-- ============================================================
-- NWCB Reports System — Run this in Supabase SQL Editor
-- ============================================================

-- 1. Create the reports table
CREATE TABLE reports (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  title       text NOT NULL CHECK (char_length(title) >= 3 AND char_length(title) <= 200),
  description text NOT NULL CHECK (char_length(description) >= 10 AND char_length(description) <= 2000),
  category    text NOT NULL CHECK (category IN ('Bug', 'Missing Item', 'Suggestion')),
  status      text NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'Confirmed', 'In Progress', 'Fixed', 'Won''t Fix')),
  upvotes     integer NOT NULL DEFAULT 0,
  voter_hashes text[] NOT NULL DEFAULT '{}'
);

-- 2. Indexes for sorting
CREATE INDEX idx_reports_created_at ON reports (created_at DESC);
CREATE INDEX idx_reports_upvotes ON reports (upvotes DESC);

-- 3. Public view (hides voter_hashes from readers)
CREATE VIEW reports_public AS
  SELECT id, created_at, title, description, category, status, upvotes
  FROM reports;

-- 4. Enable Row Level Security
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- 5. Anyone can read reports
CREATE POLICY "Anyone can read reports"
  ON reports FOR SELECT
  USING (true);

-- 6. Anyone can submit new reports (forced to safe defaults)
CREATE POLICY "Anyone can submit reports"
  ON reports FOR INSERT
  WITH CHECK (
    status = 'New'
    AND upvotes = 0
    AND voter_hashes = '{}'
  );

-- 7. Upvote function (server-side, prevents duplicates)
CREATE OR REPLACE FUNCTION upvote_report(report_id bigint, voter_hash text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Check if already voted
  IF EXISTS (
    SELECT 1 FROM reports
    WHERE id = report_id AND voter_hash = ANY(voter_hashes)
  ) THEN
    RETURN json_build_object('success', false, 'reason', 'already_voted');
  END IF;

  -- Increment upvotes and record voter
  UPDATE reports
  SET upvotes = upvotes + 1,
      voter_hashes = array_append(voter_hashes, voter_hash)
  WHERE id = report_id;

  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'reason', 'not_found');
  END IF;

  RETURN json_build_object('success', true);
END;
$$;
