#!/usr/bin/env python3
"""Export the item database (../data/*.json) to one Google-Sheets-ready
workbook — the EDITING WINDOW for the database.

  python scripts/sheet_export.py            -> docs/sheets/nwcb_database.xlsx

Upload to Google Sheets (drive.google.com -> New -> File upload -> open as
Sheets). Edit cells freely. To bring edits home: File -> Download -> .xlsx,
then run scripts/sheet_import.py (see its header).

THE JSON IN ../data/ STAYS THE SOURCE OF TRUTH. This workbook is a view of
it; the import script applies only the cells you actually changed, after
validation. Never hand-edit data/*.js (built) — run build-data.py.

Cell encoding (the import script reverses these exactly):
  - plain values            -> the cell as-is
  - list of simple values   -> comma-separated ("Barbarian, Fighter")
  - {stat: number} maps     -> one "Stat: value" per line (multiline cell)
  - nested structures       -> single-line JSON in a column named "x [JSON]"
"""
import json
import sys
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

DATA = Path(__file__).resolve().parent.parent.parent / "data"
OUT = Path(__file__).resolve().parent.parent / "docs" / "sheets" / "nwcb_database.xlsx"

# Item files only — engine config (classes, role_weights, proc profiles,
# owned_profiles, boons...) is deliberately NOT in the sheet.
FILES = [
    "gear", "enchants", "kits", "overloads", "artifacts", "buffs",
    "gear_bonuses",
    "companions", "companion_powers", "companion_enhancements", "companion_gear",
    "mounts", "mount_collars", "mount_combat_powers", "mount_equip_powers",
    "mount_insignia_bonuses",
]

README = """NWCB DATABASE — EDITING WINDOW
==============================
The website's database (JSON files in git) remains the source of truth.
This sheet is a friendly window onto it:

1. Edit any cells you like. Add a new row to add a new item (leave id
   blank — one is assigned on import). DON'T delete rows to delete items;
   deletions are done in the JSON deliberately.
2. When done: File -> Download -> Microsoft Excel (.xlsx)
3. Hand the file to Claude (or run: python scripts/sheet_import.py <file>)
   - every changed cell is validated and applied to the database
   - anything malformed is rejected with a plain-English reason
   - the site rebuilds from the database (build-data.py) and deploys

Cell formats:
  - Lists are comma-separated:            Barbarian, Fighter
  - Stat blocks are one per line:         Combat Advantage: 1560
                                          Awareness: 780
  - Columns ending in [JSON] hold nested data (equip bonuses, proc
    effects). Edit carefully — must stay valid JSON. When unsure, describe
    the change in plain words in the notes column instead.
  - If you type a value starting with + (like +3,000 Power), start the
    cell with an apostrophe: '+3,000 Power  (stops Sheets reading it as
    a formula)

Generated by scripts/sheet_export.py — regenerate any time; re-upload to
replace this sheet (File -> Import -> Replace spreadsheet).
"""


def flatten_value(v):
    """-> (cell_text, kind) where kind in scalar|list|map|json"""
    if v is None:
        return "", "scalar"
    if isinstance(v, (str, int, float, bool)):
        return v, "scalar"
    if isinstance(v, list):
        if all(isinstance(x, (str, int, float, bool)) for x in v):
            return ", ".join(str(x) for x in v), "list"
        return json.dumps(v, ensure_ascii=False, separators=(",", ":")), "json"
    if isinstance(v, dict):
        if all(isinstance(x, (str, int, float, bool)) for x in v.values()):
            return "\n".join(f"{k}: {x}" for k, x in v.items()), "map"
        return json.dumps(v, ensure_ascii=False, separators=(",", ":")), "json"
    return str(v), "scalar"


def columns_for(rows):
    """Union of keys in first-seen order; id/name first, notes/source last.
    A column gets the ' [JSON]' suffix if ANY row needs json encoding."""
    seen, order = set(), []
    for r in rows:
        for k in r:
            if k not in seen:
                seen.add(k); order.append(k)
    front = [k for k in ("id", "name") if k in seen]
    back = [k for k in ("notes", "source") if k in seen]
    mid = [k for k in order if k not in front + back]
    cols = front + mid + back
    kinds = {}
    for k in cols:
        kind = "scalar"
        for r in rows:
            if k in r:
                _, kk = flatten_value(r[k])
                if kk == "json":
                    kind = "json"; break
                if kk in ("list", "map"):
                    kind = kk
        kinds[k] = kind
    return cols, kinds


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()
    ws0 = wb.active
    ws0.title = "READ ME"
    ws0["A1"] = README
    ws0["A1"].alignment = Alignment(wrap_text=True, vertical="top")
    ws0.column_dimensions["A"].width = 110
    ws0.row_dimensions[1].height = 460

    head_font = Font(bold=True, color="FFFFFF")
    head_fill = PatternFill("solid", fgColor="2D6CDF")
    json_fill = PatternFill("solid", fgColor="6E5A36")
    total = 0

    for stem in FILES:
        path = DATA / f"{stem}.json"
        rows = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(rows, list):
            print(f"  SKIP {stem} (not a list)"); continue
        cols, kinds = columns_for(rows)
        ws = wb.create_sheet(stem[:31])
        for ci, col in enumerate(cols, 1):
            label = col + (" [JSON]" if kinds[col] == "json" else "")
            cell = ws.cell(row=1, column=ci, value=label)
            cell.font = head_font
            cell.fill = json_fill if kinds[col] == "json" else head_fill
        for ri, item in enumerate(rows, 2):
            for ci, col in enumerate(cols, 1):
                if col not in item:
                    continue
                text, _ = flatten_value(item[col])
                c = ws.cell(row=ri, column=ci, value=text)
                if isinstance(text, str) and "\n" in text:
                    c.alignment = Alignment(wrap_text=True, vertical="top")
        # usability: freeze header+name, set sane widths, add filter
        ws.freeze_panes = "C2"
        ws.auto_filter.ref = f"A1:{get_column_letter(len(cols))}{len(rows) + 1}"
        for ci, col in enumerate(cols, 1):
            w = 28 if kinds[col] in ("map", "json") else (30 if col == "name" else 14)
            ws.column_dimensions[get_column_letter(ci)].width = w
        total += len(rows)
        print(f"  {stem:28} {len(rows):6} rows  {len(cols):3} cols")

    wb.save(OUT)
    print(f"\nWrote {OUT}  ({total} items across {len(FILES)} tabs)")
    print("Upload at drive.google.com -> New -> File upload -> open with Google Sheets")


if __name__ == "__main__":
    sys.exit(main())
